// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kafka

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opDeletePrivateDomainFromPublicCommon = "DeletePrivateDomainFromPublic"

// DeletePrivateDomainFromPublicCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the DeletePrivateDomainFromPublicCommon operation. The "output" return
// value will be populated with the DeletePrivateDomainFromPublicCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DeletePrivateDomainFromPublicCommon Request to send the API call to the service.
// the "output" return value is not valid until after DeletePrivateDomainFromPublicCommon Send returns without error.
//
// See DeletePrivateDomainFromPublicCommon for more information on using the DeletePrivateDomainFromPublicCommon
// API call, and error handling.
//
//    // Example sending a request using the DeletePrivateDomainFromPublicCommonRequest method.
//    req, resp := client.DeletePrivateDomainFromPublicCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KAFKA) DeletePrivateDomainFromPublicCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opDeletePrivateDomainFromPublicCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// DeletePrivateDomainFromPublicCommon API operation for KAFKA.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KAFKA's
// API operation DeletePrivateDomainFromPublicCommon for usage and error information.
func (c *KAFKA) DeletePrivateDomainFromPublicCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.DeletePrivateDomainFromPublicCommonRequest(input)
	return out, req.Send()
}

// DeletePrivateDomainFromPublicCommonWithContext is the same as DeletePrivateDomainFromPublicCommon with the addition of
// the ability to pass a context and additional request options.
//
// See DeletePrivateDomainFromPublicCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KAFKA) DeletePrivateDomainFromPublicCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.DeletePrivateDomainFromPublicCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opDeletePrivateDomainFromPublic = "DeletePrivateDomainFromPublic"

// DeletePrivateDomainFromPublicRequest generates a "byteplus/request.Request" representing the
// client's request for the DeletePrivateDomainFromPublic operation. The "output" return
// value will be populated with the DeletePrivateDomainFromPublicCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DeletePrivateDomainFromPublicCommon Request to send the API call to the service.
// the "output" return value is not valid until after DeletePrivateDomainFromPublicCommon Send returns without error.
//
// See DeletePrivateDomainFromPublic for more information on using the DeletePrivateDomainFromPublic
// API call, and error handling.
//
//    // Example sending a request using the DeletePrivateDomainFromPublicRequest method.
//    req, resp := client.DeletePrivateDomainFromPublicRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KAFKA) DeletePrivateDomainFromPublicRequest(input *DeletePrivateDomainFromPublicInput) (req *request.Request, output *DeletePrivateDomainFromPublicOutput) {
	op := &request.Operation{
		Name:       opDeletePrivateDomainFromPublic,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DeletePrivateDomainFromPublicInput{}
	}

	output = &DeletePrivateDomainFromPublicOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// DeletePrivateDomainFromPublic API operation for KAFKA.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KAFKA's
// API operation DeletePrivateDomainFromPublic for usage and error information.
func (c *KAFKA) DeletePrivateDomainFromPublic(input *DeletePrivateDomainFromPublicInput) (*DeletePrivateDomainFromPublicOutput, error) {
	req, out := c.DeletePrivateDomainFromPublicRequest(input)
	return out, req.Send()
}

// DeletePrivateDomainFromPublicWithContext is the same as DeletePrivateDomainFromPublic with the addition of
// the ability to pass a context and additional request options.
//
// See DeletePrivateDomainFromPublic for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KAFKA) DeletePrivateDomainFromPublicWithContext(ctx byteplus.Context, input *DeletePrivateDomainFromPublicInput, opts ...request.Option) (*DeletePrivateDomainFromPublicOutput, error) {
	req, out := c.DeletePrivateDomainFromPublicRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type DeletePrivateDomainFromPublicInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	// InstanceId is a required field
	InstanceId *string `type:"string" json:",omitempty" required:"true"`
}

// String returns the string representation
func (s DeletePrivateDomainFromPublicInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s DeletePrivateDomainFromPublicInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *DeletePrivateDomainFromPublicInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "DeletePrivateDomainFromPublicInput"}
	if s.InstanceId == nil {
		invalidParams.Add(request.NewErrParamRequired("InstanceId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetInstanceId sets the InstanceId field's value.
func (s *DeletePrivateDomainFromPublicInput) SetInstanceId(v string) *DeletePrivateDomainFromPublicInput {
	s.InstanceId = &v
	return s
}

type DeletePrivateDomainFromPublicOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata
}

// String returns the string representation
func (s DeletePrivateDomainFromPublicOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s DeletePrivateDomainFromPublicOutput) GoString() string {
	return s.String()
}
