// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package ecopartneriface provides an interface to enable mocking the ECO_PARTNER service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package ecopartner

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
)

// ECOPARTNERAPI provides an interface to enable mocking the
// ecopartner.ECOPARTNER service client's API operation,
//
//    // byteplus sdk func uses an SDK service client to make a request to
//    // ECO_PARTNER.
//    func myFunc(svc ECOPARTNERAPI) bool {
//        // Make svc.CheckInvitationStatus request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := ecopartner.New(sess)
//
//        myFunc(svc)
//    }
//
type ECOPARTNERAPI interface {
	CheckInvitationStatusCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CheckInvitationStatusCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CheckInvitationStatusCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CheckInvitationStatus(*CheckInvitationStatusInput) (*CheckInvitationStatusOutput, error)
	CheckInvitationStatusWithContext(byteplus.Context, *CheckInvitationStatusInput, ...request.Option) (*CheckInvitationStatusOutput, error)
	CheckInvitationStatusRequest(*CheckInvitationStatusInput) (*request.Request, *CheckInvitationStatusOutput)

	CreateInvitationLinkCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateInvitationLinkCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateInvitationLinkCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateInvitationLink(*CreateInvitationLinkInput) (*CreateInvitationLinkOutput, error)
	CreateInvitationLinkWithContext(byteplus.Context, *CreateInvitationLinkInput, ...request.Option) (*CreateInvitationLinkOutput, error)
	CreateInvitationLinkRequest(*CreateInvitationLinkInput) (*request.Request, *CreateInvitationLinkOutput)

	CreateUniqueInvitationLinkCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateUniqueInvitationLinkCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateUniqueInvitationLinkCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateUniqueInvitationLink(*CreateUniqueInvitationLinkInput) (*CreateUniqueInvitationLinkOutput, error)
	CreateUniqueInvitationLinkWithContext(byteplus.Context, *CreateUniqueInvitationLinkInput, ...request.Option) (*CreateUniqueInvitationLinkOutput, error)
	CreateUniqueInvitationLinkRequest(*CreateUniqueInvitationLinkInput) (*request.Request, *CreateUniqueInvitationLinkOutput)

	GetCustomerDetailsByTypeCommon(*map[string]interface{}) (*map[string]interface{}, error)
	GetCustomerDetailsByTypeCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetCustomerDetailsByTypeCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetCustomerDetailsByType(*GetCustomerDetailsByTypeInput) (*GetCustomerDetailsByTypeOutput, error)
	GetCustomerDetailsByTypeWithContext(byteplus.Context, *GetCustomerDetailsByTypeInput, ...request.Option) (*GetCustomerDetailsByTypeOutput, error)
	GetCustomerDetailsByTypeRequest(*GetCustomerDetailsByTypeInput) (*request.Request, *GetCustomerDetailsByTypeOutput)

	GetCustomerDetailsByUIDCommon(*map[string]interface{}) (*map[string]interface{}, error)
	GetCustomerDetailsByUIDCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetCustomerDetailsByUIDCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetCustomerDetailsByUID(*GetCustomerDetailsByUIDInput) (*GetCustomerDetailsByUIDOutput, error)
	GetCustomerDetailsByUIDWithContext(byteplus.Context, *GetCustomerDetailsByUIDInput, ...request.Option) (*GetCustomerDetailsByUIDOutput, error)
	GetCustomerDetailsByUIDRequest(*GetCustomerDetailsByUIDInput) (*request.Request, *GetCustomerDetailsByUIDOutput)

	GetQuotaInformationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	GetQuotaInformationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetQuotaInformationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetQuotaInformation(*GetQuotaInformationInput) (*GetQuotaInformationOutput, error)
	GetQuotaInformationWithContext(byteplus.Context, *GetQuotaInformationInput, ...request.Option) (*GetQuotaInformationOutput, error)
	GetQuotaInformationRequest(*GetQuotaInformationInput) (*request.Request, *GetQuotaInformationOutput)

	ModifyQuotaCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyQuotaCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyQuotaCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyQuota(*ModifyQuotaInput) (*ModifyQuotaOutput, error)
	ModifyQuotaWithContext(byteplus.Context, *ModifyQuotaInput, ...request.Option) (*ModifyQuotaOutput, error)
	ModifyQuotaRequest(*ModifyQuotaInput) (*request.Request, *ModifyQuotaOutput)

	SettleQuotaPaymentCommon(*map[string]interface{}) (*map[string]interface{}, error)
	SettleQuotaPaymentCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	SettleQuotaPaymentCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	SettleQuotaPayment(*SettleQuotaPaymentInput) (*SettleQuotaPaymentOutput, error)
	SettleQuotaPaymentWithContext(byteplus.Context, *SettleQuotaPaymentInput, ...request.Option) (*SettleQuotaPaymentOutput, error)
	SettleQuotaPaymentRequest(*SettleQuotaPaymentInput) (*request.Request, *SettleQuotaPaymentOutput)
}

var _ ECOPARTNERAPI = (*ECOPARTNER)(nil)
