// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package quota

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opListProductQuotaDimensionsCommon = "ListProductQuotaDimensions"

// ListProductQuotaDimensionsCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the ListProductQuotaDimensionsCommon operation. The "output" return
// value will be populated with the ListProductQuotaDimensionsCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ListProductQuotaDimensionsCommon Request to send the API call to the service.
// the "output" return value is not valid until after ListProductQuotaDimensionsCommon Send returns without error.
//
// See ListProductQuotaDimensionsCommon for more information on using the ListProductQuotaDimensionsCommon
// API call, and error handling.
//
//    // Example sending a request using the ListProductQuotaDimensionsCommonRequest method.
//    req, resp := client.ListProductQuotaDimensionsCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *QUOTA) ListProductQuotaDimensionsCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opListProductQuotaDimensionsCommon,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	return
}

// ListProductQuotaDimensionsCommon API operation for QUOTA.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for QUOTA's
// API operation ListProductQuotaDimensionsCommon for usage and error information.
func (c *QUOTA) ListProductQuotaDimensionsCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.ListProductQuotaDimensionsCommonRequest(input)
	return out, req.Send()
}

// ListProductQuotaDimensionsCommonWithContext is the same as ListProductQuotaDimensionsCommon with the addition of
// the ability to pass a context and additional request options.
//
// See ListProductQuotaDimensionsCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *QUOTA) ListProductQuotaDimensionsCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.ListProductQuotaDimensionsCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opListProductQuotaDimensions = "ListProductQuotaDimensions"

// ListProductQuotaDimensionsRequest generates a "byteplus/request.Request" representing the
// client's request for the ListProductQuotaDimensions operation. The "output" return
// value will be populated with the ListProductQuotaDimensionsCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ListProductQuotaDimensionsCommon Request to send the API call to the service.
// the "output" return value is not valid until after ListProductQuotaDimensionsCommon Send returns without error.
//
// See ListProductQuotaDimensions for more information on using the ListProductQuotaDimensions
// API call, and error handling.
//
//    // Example sending a request using the ListProductQuotaDimensionsRequest method.
//    req, resp := client.ListProductQuotaDimensionsRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *QUOTA) ListProductQuotaDimensionsRequest(input *ListProductQuotaDimensionsInput) (req *request.Request, output *ListProductQuotaDimensionsOutput) {
	op := &request.Operation{
		Name:       opListProductQuotaDimensions,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ListProductQuotaDimensionsInput{}
	}

	output = &ListProductQuotaDimensionsOutput{}
	req = c.newRequest(op, input, output)

	return
}

// ListProductQuotaDimensions API operation for QUOTA.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for QUOTA's
// API operation ListProductQuotaDimensions for usage and error information.
func (c *QUOTA) ListProductQuotaDimensions(input *ListProductQuotaDimensionsInput) (*ListProductQuotaDimensionsOutput, error) {
	req, out := c.ListProductQuotaDimensionsRequest(input)
	return out, req.Send()
}

// ListProductQuotaDimensionsWithContext is the same as ListProductQuotaDimensions with the addition of
// the ability to pass a context and additional request options.
//
// See ListProductQuotaDimensions for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *QUOTA) ListProductQuotaDimensionsWithContext(ctx byteplus.Context, input *ListProductQuotaDimensionsInput, opts ...request.Option) (*ListProductQuotaDimensionsOutput, error) {
	req, out := c.ListProductQuotaDimensionsRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type DimensionForListProductQuotaDimensionsOutput struct {
	_ struct{} `type:"structure"`

	DimensionCode *string `type:"string"`

	DimensionName *string `type:"string"`

	DimensionValues []*DimensionValueForListProductQuotaDimensionsOutput `type:"list"`
}

// String returns the string representation
func (s DimensionForListProductQuotaDimensionsOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s DimensionForListProductQuotaDimensionsOutput) GoString() string {
	return s.String()
}

// SetDimensionCode sets the DimensionCode field's value.
func (s *DimensionForListProductQuotaDimensionsOutput) SetDimensionCode(v string) *DimensionForListProductQuotaDimensionsOutput {
	s.DimensionCode = &v
	return s
}

// SetDimensionName sets the DimensionName field's value.
func (s *DimensionForListProductQuotaDimensionsOutput) SetDimensionName(v string) *DimensionForListProductQuotaDimensionsOutput {
	s.DimensionName = &v
	return s
}

// SetDimensionValues sets the DimensionValues field's value.
func (s *DimensionForListProductQuotaDimensionsOutput) SetDimensionValues(v []*DimensionValueForListProductQuotaDimensionsOutput) *DimensionForListProductQuotaDimensionsOutput {
	s.DimensionValues = v
	return s
}

type DimensionValueForListProductQuotaDimensionsOutput struct {
	_ struct{} `type:"structure"`

	DimensionValueCode *string `type:"string"`

	DimensionValueName *string `type:"string"`
}

// String returns the string representation
func (s DimensionValueForListProductQuotaDimensionsOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s DimensionValueForListProductQuotaDimensionsOutput) GoString() string {
	return s.String()
}

// SetDimensionValueCode sets the DimensionValueCode field's value.
func (s *DimensionValueForListProductQuotaDimensionsOutput) SetDimensionValueCode(v string) *DimensionValueForListProductQuotaDimensionsOutput {
	s.DimensionValueCode = &v
	return s
}

// SetDimensionValueName sets the DimensionValueName field's value.
func (s *DimensionValueForListProductQuotaDimensionsOutput) SetDimensionValueName(v string) *DimensionValueForListProductQuotaDimensionsOutput {
	s.DimensionValueName = &v
	return s
}

type ListProductQuotaDimensionsInput struct {
	_ struct{} `type:"structure"`

	// ProviderCode is a required field
	ProviderCode *string `type:"string" required:"true"`

	QuotaType *string `type:"string"`
}

// String returns the string representation
func (s ListProductQuotaDimensionsInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ListProductQuotaDimensionsInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *ListProductQuotaDimensionsInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "ListProductQuotaDimensionsInput"}
	if s.ProviderCode == nil {
		invalidParams.Add(request.NewErrParamRequired("ProviderCode"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetProviderCode sets the ProviderCode field's value.
func (s *ListProductQuotaDimensionsInput) SetProviderCode(v string) *ListProductQuotaDimensionsInput {
	s.ProviderCode = &v
	return s
}

// SetQuotaType sets the QuotaType field's value.
func (s *ListProductQuotaDimensionsInput) SetQuotaType(v string) *ListProductQuotaDimensionsInput {
	s.QuotaType = &v
	return s
}

type ListProductQuotaDimensionsOutput struct {
	_ struct{} `type:"structure"`

	Metadata *response.ResponseMetadata

	Dimensions []*DimensionForListProductQuotaDimensionsOutput `type:"list"`

	ResultsNum *int32 `type:"int32"`
}

// String returns the string representation
func (s ListProductQuotaDimensionsOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ListProductQuotaDimensionsOutput) GoString() string {
	return s.String()
}

// SetDimensions sets the Dimensions field's value.
func (s *ListProductQuotaDimensionsOutput) SetDimensions(v []*DimensionForListProductQuotaDimensionsOutput) *ListProductQuotaDimensionsOutput {
	s.Dimensions = v
	return s
}

// SetResultsNum sets the ResultsNum field's value.
func (s *ListProductQuotaDimensionsOutput) SetResultsNum(v int32) *ListProductQuotaDimensionsOutput {
	s.ResultsNum = &v
	return s
}
