// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opGetMediaCommon = "GetMedia"

// GetMediaCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the GetMediaCommon operation. The "output" return
// value will be populated with the GetMediaCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetMediaCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetMediaCommon Send returns without error.
//
// See GetMediaCommon for more information on using the GetMediaCommon
// API call, and error handling.
//
//    // Example sending a request using the GetMediaCommonRequest method.
//    req, resp := client.GetMediaCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetMediaCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opGetMediaCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetMediaCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetMediaCommon for usage and error information.
func (c *KICKART) GetMediaCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.GetMediaCommonRequest(input)
	return out, req.Send()
}

// GetMediaCommonWithContext is the same as GetMediaCommon with the addition of
// the ability to pass a context and additional request options.
//
// See GetMediaCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetMediaCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.GetMediaCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opGetMedia = "GetMedia"

// GetMediaRequest generates a "byteplus/request.Request" representing the
// client's request for the GetMedia operation. The "output" return
// value will be populated with the GetMediaCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetMediaCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetMediaCommon Send returns without error.
//
// See GetMedia for more information on using the GetMedia
// API call, and error handling.
//
//    // Example sending a request using the GetMediaRequest method.
//    req, resp := client.GetMediaRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetMediaRequest(input *GetMediaInput) (req *request.Request, output *GetMediaOutput) {
	op := &request.Operation{
		Name:       opGetMedia,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GetMediaInput{}
	}

	output = &GetMediaOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetMedia API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetMedia for usage and error information.
func (c *KICKART) GetMedia(input *GetMediaInput) (*GetMediaOutput, error) {
	req, out := c.GetMediaRequest(input)
	return out, req.Send()
}

// GetMediaWithContext is the same as GetMedia with the addition of
// the ability to pass a context and additional request options.
//
// See GetMedia for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetMediaWithContext(ctx byteplus.Context, input *GetMediaInput, opts ...request.Option) (*GetMediaOutput, error) {
	req, out := c.GetMediaRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type GetMediaInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	MediaIds []*string `type:"list"`
}

// String returns the string representation
func (s GetMediaInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetMediaInput) GoString() string {
	return s.String()
}

// SetMediaIds sets the MediaIds field's value.
func (s *GetMediaInput) SetMediaIds(v []*string) *GetMediaInput {
	s.MediaIds = v
	return s
}

type GetMediaOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	Medias []*string `type:"list"`
}

// String returns the string representation
func (s GetMediaOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetMediaOutput) GoString() string {
	return s.String()
}

// SetMedias sets the Medias field's value.
func (s *GetMediaOutput) SetMedias(v []*string) *GetMediaOutput {
	s.Medias = v
	return s
}
