// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opDeleteTaskItemCommon = "DeleteTaskItem"

// DeleteTaskItemCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the DeleteTaskItemCommon operation. The "output" return
// value will be populated with the DeleteTaskItemCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DeleteTaskItemCommon Request to send the API call to the service.
// the "output" return value is not valid until after DeleteTaskItemCommon Send returns without error.
//
// See DeleteTaskItemCommon for more information on using the DeleteTaskItemCommon
// API call, and error handling.
//
//    // Example sending a request using the DeleteTaskItemCommonRequest method.
//    req, resp := client.DeleteTaskItemCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) DeleteTaskItemCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opDeleteTaskItemCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// DeleteTaskItemCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation DeleteTaskItemCommon for usage and error information.
func (c *KICKART) DeleteTaskItemCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.DeleteTaskItemCommonRequest(input)
	return out, req.Send()
}

// DeleteTaskItemCommonWithContext is the same as DeleteTaskItemCommon with the addition of
// the ability to pass a context and additional request options.
//
// See DeleteTaskItemCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) DeleteTaskItemCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.DeleteTaskItemCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opDeleteTaskItem = "DeleteTaskItem"

// DeleteTaskItemRequest generates a "byteplus/request.Request" representing the
// client's request for the DeleteTaskItem operation. The "output" return
// value will be populated with the DeleteTaskItemCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DeleteTaskItemCommon Request to send the API call to the service.
// the "output" return value is not valid until after DeleteTaskItemCommon Send returns without error.
//
// See DeleteTaskItem for more information on using the DeleteTaskItem
// API call, and error handling.
//
//    // Example sending a request using the DeleteTaskItemRequest method.
//    req, resp := client.DeleteTaskItemRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) DeleteTaskItemRequest(input *DeleteTaskItemInput) (req *request.Request, output *DeleteTaskItemOutput) {
	op := &request.Operation{
		Name:       opDeleteTaskItem,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DeleteTaskItemInput{}
	}

	output = &DeleteTaskItemOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// DeleteTaskItem API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation DeleteTaskItem for usage and error information.
func (c *KICKART) DeleteTaskItem(input *DeleteTaskItemInput) (*DeleteTaskItemOutput, error) {
	req, out := c.DeleteTaskItemRequest(input)
	return out, req.Send()
}

// DeleteTaskItemWithContext is the same as DeleteTaskItem with the addition of
// the ability to pass a context and additional request options.
//
// See DeleteTaskItem for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) DeleteTaskItemWithContext(ctx byteplus.Context, input *DeleteTaskItemInput, opts ...request.Option) (*DeleteTaskItemOutput, error) {
	req, out := c.DeleteTaskItemRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type DeleteTaskItemInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Id *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s DeleteTaskItemInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteTaskItemInput) GoString() string {
	return s.String()
}

// SetId sets the Id field's value.
func (s *DeleteTaskItemInput) SetId(v string) *DeleteTaskItemInput {
	s.Id = &v
	return s
}

type DeleteTaskItemOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata
}

// String returns the string representation
func (s DeleteTaskItemOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteTaskItemOutput) GoString() string {
	return s.String()
}
