// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opGetCompositionCommon = "GetComposition"

// GetCompositionCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the GetCompositionCommon operation. The "output" return
// value will be populated with the GetCompositionCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetCompositionCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetCompositionCommon Send returns without error.
//
// See GetCompositionCommon for more information on using the GetCompositionCommon
// API call, and error handling.
//
//    // Example sending a request using the GetCompositionCommonRequest method.
//    req, resp := client.GetCompositionCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetCompositionCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opGetCompositionCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetCompositionCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetCompositionCommon for usage and error information.
func (c *KICKART) GetCompositionCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.GetCompositionCommonRequest(input)
	return out, req.Send()
}

// GetCompositionCommonWithContext is the same as GetCompositionCommon with the addition of
// the ability to pass a context and additional request options.
//
// See GetCompositionCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetCompositionCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.GetCompositionCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opGetComposition = "GetComposition"

// GetCompositionRequest generates a "byteplus/request.Request" representing the
// client's request for the GetComposition operation. The "output" return
// value will be populated with the GetCompositionCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetCompositionCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetCompositionCommon Send returns without error.
//
// See GetComposition for more information on using the GetComposition
// API call, and error handling.
//
//    // Example sending a request using the GetCompositionRequest method.
//    req, resp := client.GetCompositionRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetCompositionRequest(input *GetCompositionInput) (req *request.Request, output *GetCompositionOutput) {
	op := &request.Operation{
		Name:       opGetComposition,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GetCompositionInput{}
	}

	output = &GetCompositionOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetComposition API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetComposition for usage and error information.
func (c *KICKART) GetComposition(input *GetCompositionInput) (*GetCompositionOutput, error) {
	req, out := c.GetCompositionRequest(input)
	return out, req.Send()
}

// GetCompositionWithContext is the same as GetComposition with the addition of
// the ability to pass a context and additional request options.
//
// See GetComposition for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetCompositionWithContext(ctx byteplus.Context, input *GetCompositionInput, opts ...request.Option) (*GetCompositionOutput, error) {
	req, out := c.GetCompositionRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type GetCompositionInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Id *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s GetCompositionInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetCompositionInput) GoString() string {
	return s.String()
}

// SetId sets the Id field's value.
func (s *GetCompositionInput) SetId(v string) *GetCompositionInput {
	s.Id = &v
	return s
}

type GetCompositionOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	CompositionParam *string `type:"string" json:",omitempty"`

	Content *string `type:"string" json:",omitempty"`

	CreateTime *int64 `type:"int64" json:",omitempty"`

	RunningTaskIds []*string `type:"list"`

	UpdateExportVideos *string `type:"string" json:",omitempty"`

	UpdateTime *int64 `type:"int64" json:",omitempty"`
}

// String returns the string representation
func (s GetCompositionOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetCompositionOutput) GoString() string {
	return s.String()
}

// SetCompositionParam sets the CompositionParam field's value.
func (s *GetCompositionOutput) SetCompositionParam(v string) *GetCompositionOutput {
	s.CompositionParam = &v
	return s
}

// SetContent sets the Content field's value.
func (s *GetCompositionOutput) SetContent(v string) *GetCompositionOutput {
	s.Content = &v
	return s
}

// SetCreateTime sets the CreateTime field's value.
func (s *GetCompositionOutput) SetCreateTime(v int64) *GetCompositionOutput {
	s.CreateTime = &v
	return s
}

// SetRunningTaskIds sets the RunningTaskIds field's value.
func (s *GetCompositionOutput) SetRunningTaskIds(v []*string) *GetCompositionOutput {
	s.RunningTaskIds = v
	return s
}

// SetUpdateExportVideos sets the UpdateExportVideos field's value.
func (s *GetCompositionOutput) SetUpdateExportVideos(v string) *GetCompositionOutput {
	s.UpdateExportVideos = &v
	return s
}

// SetUpdateTime sets the UpdateTime field's value.
func (s *GetCompositionOutput) SetUpdateTime(v int64) *GetCompositionOutput {
	s.UpdateTime = &v
	return s
}
