// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opGetAiTemplateTaskStatusCommon = "GetAiTemplateTaskStatus"

// GetAiTemplateTaskStatusCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the GetAiTemplateTaskStatusCommon operation. The "output" return
// value will be populated with the GetAiTemplateTaskStatusCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetAiTemplateTaskStatusCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetAiTemplateTaskStatusCommon Send returns without error.
//
// See GetAiTemplateTaskStatusCommon for more information on using the GetAiTemplateTaskStatusCommon
// API call, and error handling.
//
//    // Example sending a request using the GetAiTemplateTaskStatusCommonRequest method.
//    req, resp := client.GetAiTemplateTaskStatusCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetAiTemplateTaskStatusCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opGetAiTemplateTaskStatusCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetAiTemplateTaskStatusCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetAiTemplateTaskStatusCommon for usage and error information.
func (c *KICKART) GetAiTemplateTaskStatusCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.GetAiTemplateTaskStatusCommonRequest(input)
	return out, req.Send()
}

// GetAiTemplateTaskStatusCommonWithContext is the same as GetAiTemplateTaskStatusCommon with the addition of
// the ability to pass a context and additional request options.
//
// See GetAiTemplateTaskStatusCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetAiTemplateTaskStatusCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.GetAiTemplateTaskStatusCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opGetAiTemplateTaskStatus = "GetAiTemplateTaskStatus"

// GetAiTemplateTaskStatusRequest generates a "byteplus/request.Request" representing the
// client's request for the GetAiTemplateTaskStatus operation. The "output" return
// value will be populated with the GetAiTemplateTaskStatusCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetAiTemplateTaskStatusCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetAiTemplateTaskStatusCommon Send returns without error.
//
// See GetAiTemplateTaskStatus for more information on using the GetAiTemplateTaskStatus
// API call, and error handling.
//
//    // Example sending a request using the GetAiTemplateTaskStatusRequest method.
//    req, resp := client.GetAiTemplateTaskStatusRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetAiTemplateTaskStatusRequest(input *GetAiTemplateTaskStatusInput) (req *request.Request, output *GetAiTemplateTaskStatusOutput) {
	op := &request.Operation{
		Name:       opGetAiTemplateTaskStatus,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GetAiTemplateTaskStatusInput{}
	}

	output = &GetAiTemplateTaskStatusOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetAiTemplateTaskStatus API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetAiTemplateTaskStatus for usage and error information.
func (c *KICKART) GetAiTemplateTaskStatus(input *GetAiTemplateTaskStatusInput) (*GetAiTemplateTaskStatusOutput, error) {
	req, out := c.GetAiTemplateTaskStatusRequest(input)
	return out, req.Send()
}

// GetAiTemplateTaskStatusWithContext is the same as GetAiTemplateTaskStatus with the addition of
// the ability to pass a context and additional request options.
//
// See GetAiTemplateTaskStatus for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetAiTemplateTaskStatusWithContext(ctx byteplus.Context, input *GetAiTemplateTaskStatusInput, opts ...request.Option) (*GetAiTemplateTaskStatusOutput, error) {
	req, out := c.GetAiTemplateTaskStatusRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type GetAiTemplateTaskStatusInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	TaskId []*string `type:"list"`
}

// String returns the string representation
func (s GetAiTemplateTaskStatusInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetAiTemplateTaskStatusInput) GoString() string {
	return s.String()
}

// SetTaskId sets the TaskId field's value.
func (s *GetAiTemplateTaskStatusInput) SetTaskId(v []*string) *GetAiTemplateTaskStatusInput {
	s.TaskId = v
	return s
}

type GetAiTemplateTaskStatusOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	TaskResult []*string `type:"list"`
}

// String returns the string representation
func (s GetAiTemplateTaskStatusOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetAiTemplateTaskStatusOutput) GoString() string {
	return s.String()
}

// SetTaskResult sets the TaskResult field's value.
func (s *GetAiTemplateTaskStatusOutput) SetTaskResult(v []*string) *GetAiTemplateTaskStatusOutput {
	s.TaskResult = v
	return s
}
