// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opExportEditorVideoCommon = "ExportEditorVideo"

// ExportEditorVideoCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the ExportEditorVideoCommon operation. The "output" return
// value will be populated with the ExportEditorVideoCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ExportEditorVideoCommon Request to send the API call to the service.
// the "output" return value is not valid until after ExportEditorVideoCommon Send returns without error.
//
// See ExportEditorVideoCommon for more information on using the ExportEditorVideoCommon
// API call, and error handling.
//
//    // Example sending a request using the ExportEditorVideoCommonRequest method.
//    req, resp := client.ExportEditorVideoCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) ExportEditorVideoCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opExportEditorVideoCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ExportEditorVideoCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation ExportEditorVideoCommon for usage and error information.
func (c *KICKART) ExportEditorVideoCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.ExportEditorVideoCommonRequest(input)
	return out, req.Send()
}

// ExportEditorVideoCommonWithContext is the same as ExportEditorVideoCommon with the addition of
// the ability to pass a context and additional request options.
//
// See ExportEditorVideoCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) ExportEditorVideoCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.ExportEditorVideoCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opExportEditorVideo = "ExportEditorVideo"

// ExportEditorVideoRequest generates a "byteplus/request.Request" representing the
// client's request for the ExportEditorVideo operation. The "output" return
// value will be populated with the ExportEditorVideoCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ExportEditorVideoCommon Request to send the API call to the service.
// the "output" return value is not valid until after ExportEditorVideoCommon Send returns without error.
//
// See ExportEditorVideo for more information on using the ExportEditorVideo
// API call, and error handling.
//
//    // Example sending a request using the ExportEditorVideoRequest method.
//    req, resp := client.ExportEditorVideoRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) ExportEditorVideoRequest(input *ExportEditorVideoInput) (req *request.Request, output *ExportEditorVideoOutput) {
	op := &request.Operation{
		Name:       opExportEditorVideo,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ExportEditorVideoInput{}
	}

	output = &ExportEditorVideoOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ExportEditorVideo API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation ExportEditorVideo for usage and error information.
func (c *KICKART) ExportEditorVideo(input *ExportEditorVideoInput) (*ExportEditorVideoOutput, error) {
	req, out := c.ExportEditorVideoRequest(input)
	return out, req.Send()
}

// ExportEditorVideoWithContext is the same as ExportEditorVideo with the addition of
// the ability to pass a context and additional request options.
//
// See ExportEditorVideo for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) ExportEditorVideoWithContext(ctx byteplus.Context, input *ExportEditorVideoInput, opts ...request.Option) (*ExportEditorVideoOutput, error) {
	req, out := c.ExportEditorVideoRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type ExportEditorVideoInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Crf *int32 `type:"int32" json:",omitempty"`

	DraftId *string `type:"string" json:",omitempty"`

	Duration *int32 `type:"int32" json:",omitempty"`

	Fps *int32 `type:"int32" json:",omitempty"`

	Height *int32 `type:"int32" json:",omitempty"`

	Watermark *bool `type:"boolean" json:",omitempty"`

	Width *int32 `type:"int32" json:",omitempty"`
}

// String returns the string representation
func (s ExportEditorVideoInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ExportEditorVideoInput) GoString() string {
	return s.String()
}

// SetCrf sets the Crf field's value.
func (s *ExportEditorVideoInput) SetCrf(v int32) *ExportEditorVideoInput {
	s.Crf = &v
	return s
}

// SetDraftId sets the DraftId field's value.
func (s *ExportEditorVideoInput) SetDraftId(v string) *ExportEditorVideoInput {
	s.DraftId = &v
	return s
}

// SetDuration sets the Duration field's value.
func (s *ExportEditorVideoInput) SetDuration(v int32) *ExportEditorVideoInput {
	s.Duration = &v
	return s
}

// SetFps sets the Fps field's value.
func (s *ExportEditorVideoInput) SetFps(v int32) *ExportEditorVideoInput {
	s.Fps = &v
	return s
}

// SetHeight sets the Height field's value.
func (s *ExportEditorVideoInput) SetHeight(v int32) *ExportEditorVideoInput {
	s.Height = &v
	return s
}

// SetWatermark sets the Watermark field's value.
func (s *ExportEditorVideoInput) SetWatermark(v bool) *ExportEditorVideoInput {
	s.Watermark = &v
	return s
}

// SetWidth sets the Width field's value.
func (s *ExportEditorVideoInput) SetWidth(v int32) *ExportEditorVideoInput {
	s.Width = &v
	return s
}

type ExportEditorVideoOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	TaskId *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ExportEditorVideoOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ExportEditorVideoOutput) GoString() string {
	return s.String()
}

// SetTaskId sets the TaskId field's value.
func (s *ExportEditorVideoOutput) SetTaskId(v string) *ExportEditorVideoOutput {
	s.TaskId = &v
	return s
}
