// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opGetBlockDetailCommon = "GetBlockDetail"

// GetBlockDetailCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the GetBlockDetailCommon operation. The "output" return
// value will be populated with the GetBlockDetailCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetBlockDetailCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetBlockDetailCommon Send returns without error.
//
// See GetBlockDetailCommon for more information on using the GetBlockDetailCommon
// API call, and error handling.
//
//    // Example sending a request using the GetBlockDetailCommonRequest method.
//    req, resp := client.GetBlockDetailCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetBlockDetailCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opGetBlockDetailCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetBlockDetailCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetBlockDetailCommon for usage and error information.
func (c *KICKART) GetBlockDetailCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.GetBlockDetailCommonRequest(input)
	return out, req.Send()
}

// GetBlockDetailCommonWithContext is the same as GetBlockDetailCommon with the addition of
// the ability to pass a context and additional request options.
//
// See GetBlockDetailCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetBlockDetailCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.GetBlockDetailCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opGetBlockDetail = "GetBlockDetail"

// GetBlockDetailRequest generates a "byteplus/request.Request" representing the
// client's request for the GetBlockDetail operation. The "output" return
// value will be populated with the GetBlockDetailCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetBlockDetailCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetBlockDetailCommon Send returns without error.
//
// See GetBlockDetail for more information on using the GetBlockDetail
// API call, and error handling.
//
//    // Example sending a request using the GetBlockDetailRequest method.
//    req, resp := client.GetBlockDetailRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetBlockDetailRequest(input *GetBlockDetailInput) (req *request.Request, output *GetBlockDetailOutput) {
	op := &request.Operation{
		Name:       opGetBlockDetail,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GetBlockDetailInput{}
	}

	output = &GetBlockDetailOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetBlockDetail API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetBlockDetail for usage and error information.
func (c *KICKART) GetBlockDetail(input *GetBlockDetailInput) (*GetBlockDetailOutput, error) {
	req, out := c.GetBlockDetailRequest(input)
	return out, req.Send()
}

// GetBlockDetailWithContext is the same as GetBlockDetail with the addition of
// the ability to pass a context and additional request options.
//
// See GetBlockDetail for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetBlockDetailWithContext(ctx byteplus.Context, input *GetBlockDetailInput, opts ...request.Option) (*GetBlockDetailOutput, error) {
	req, out := c.GetBlockDetailRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type GetBlockDetailInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Id *string `type:"string" json:",omitempty"`

	Lang *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s GetBlockDetailInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetBlockDetailInput) GoString() string {
	return s.String()
}

// SetId sets the Id field's value.
func (s *GetBlockDetailInput) SetId(v string) *GetBlockDetailInput {
	s.Id = &v
	return s
}

// SetLang sets the Lang field's value.
func (s *GetBlockDetailInput) SetLang(v string) *GetBlockDetailInput {
	s.Lang = &v
	return s
}

type GetBlockDetailOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	Block *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s GetBlockDetailOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetBlockDetailOutput) GoString() string {
	return s.String()
}

// SetBlock sets the Block field's value.
func (s *GetBlockDetailOutput) SetBlock(v string) *GetBlockDetailOutput {
	s.Block = &v
	return s
}
