// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opGenProductIntroVideoCommon = "GenProductIntroVideo"

// GenProductIntroVideoCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the GenProductIntroVideoCommon operation. The "output" return
// value will be populated with the GenProductIntroVideoCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GenProductIntroVideoCommon Request to send the API call to the service.
// the "output" return value is not valid until after GenProductIntroVideoCommon Send returns without error.
//
// See GenProductIntroVideoCommon for more information on using the GenProductIntroVideoCommon
// API call, and error handling.
//
//    // Example sending a request using the GenProductIntroVideoCommonRequest method.
//    req, resp := client.GenProductIntroVideoCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GenProductIntroVideoCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opGenProductIntroVideoCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GenProductIntroVideoCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GenProductIntroVideoCommon for usage and error information.
func (c *KICKART) GenProductIntroVideoCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.GenProductIntroVideoCommonRequest(input)
	return out, req.Send()
}

// GenProductIntroVideoCommonWithContext is the same as GenProductIntroVideoCommon with the addition of
// the ability to pass a context and additional request options.
//
// See GenProductIntroVideoCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GenProductIntroVideoCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.GenProductIntroVideoCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opGenProductIntroVideo = "GenProductIntroVideo"

// GenProductIntroVideoRequest generates a "byteplus/request.Request" representing the
// client's request for the GenProductIntroVideo operation. The "output" return
// value will be populated with the GenProductIntroVideoCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GenProductIntroVideoCommon Request to send the API call to the service.
// the "output" return value is not valid until after GenProductIntroVideoCommon Send returns without error.
//
// See GenProductIntroVideo for more information on using the GenProductIntroVideo
// API call, and error handling.
//
//    // Example sending a request using the GenProductIntroVideoRequest method.
//    req, resp := client.GenProductIntroVideoRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GenProductIntroVideoRequest(input *GenProductIntroVideoInput) (req *request.Request, output *GenProductIntroVideoOutput) {
	op := &request.Operation{
		Name:       opGenProductIntroVideo,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GenProductIntroVideoInput{}
	}

	output = &GenProductIntroVideoOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GenProductIntroVideo API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GenProductIntroVideo for usage and error information.
func (c *KICKART) GenProductIntroVideo(input *GenProductIntroVideoInput) (*GenProductIntroVideoOutput, error) {
	req, out := c.GenProductIntroVideoRequest(input)
	return out, req.Send()
}

// GenProductIntroVideoWithContext is the same as GenProductIntroVideo with the addition of
// the ability to pass a context and additional request options.
//
// See GenProductIntroVideo for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GenProductIntroVideoWithContext(ctx byteplus.Context, input *GenProductIntroVideoInput, opts ...request.Option) (*GenProductIntroVideoOutput, error) {
	req, out := c.GenProductIntroVideoRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type GenProductIntroVideoInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	CompositionId *string `type:"string" json:",omitempty"`

	Lang *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s GenProductIntroVideoInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GenProductIntroVideoInput) GoString() string {
	return s.String()
}

// SetCompositionId sets the CompositionId field's value.
func (s *GenProductIntroVideoInput) SetCompositionId(v string) *GenProductIntroVideoInput {
	s.CompositionId = &v
	return s
}

// SetLang sets the Lang field's value.
func (s *GenProductIntroVideoInput) SetLang(v string) *GenProductIntroVideoInput {
	s.Lang = &v
	return s
}

type GenProductIntroVideoOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	NewBlocks []*string `type:"list"`

	TaskId *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s GenProductIntroVideoOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GenProductIntroVideoOutput) GoString() string {
	return s.String()
}

// SetNewBlocks sets the NewBlocks field's value.
func (s *GenProductIntroVideoOutput) SetNewBlocks(v []*string) *GenProductIntroVideoOutput {
	s.NewBlocks = v
	return s
}

// SetTaskId sets the TaskId field's value.
func (s *GenProductIntroVideoOutput) SetTaskId(v string) *GenProductIntroVideoOutput {
	s.TaskId = &v
	return s
}
