// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opBatchDeleteMediaCommon = "BatchDeleteMedia"

// BatchDeleteMediaCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the BatchDeleteMediaCommon operation. The "output" return
// value will be populated with the BatchDeleteMediaCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned BatchDeleteMediaCommon Request to send the API call to the service.
// the "output" return value is not valid until after BatchDeleteMediaCommon Send returns without error.
//
// See BatchDeleteMediaCommon for more information on using the BatchDeleteMediaCommon
// API call, and error handling.
//
//    // Example sending a request using the BatchDeleteMediaCommonRequest method.
//    req, resp := client.BatchDeleteMediaCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) BatchDeleteMediaCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opBatchDeleteMediaCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// BatchDeleteMediaCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation BatchDeleteMediaCommon for usage and error information.
func (c *KICKART) BatchDeleteMediaCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.BatchDeleteMediaCommonRequest(input)
	return out, req.Send()
}

// BatchDeleteMediaCommonWithContext is the same as BatchDeleteMediaCommon with the addition of
// the ability to pass a context and additional request options.
//
// See BatchDeleteMediaCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) BatchDeleteMediaCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.BatchDeleteMediaCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opBatchDeleteMedia = "BatchDeleteMedia"

// BatchDeleteMediaRequest generates a "byteplus/request.Request" representing the
// client's request for the BatchDeleteMedia operation. The "output" return
// value will be populated with the BatchDeleteMediaCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned BatchDeleteMediaCommon Request to send the API call to the service.
// the "output" return value is not valid until after BatchDeleteMediaCommon Send returns without error.
//
// See BatchDeleteMedia for more information on using the BatchDeleteMedia
// API call, and error handling.
//
//    // Example sending a request using the BatchDeleteMediaRequest method.
//    req, resp := client.BatchDeleteMediaRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) BatchDeleteMediaRequest(input *BatchDeleteMediaInput) (req *request.Request, output *BatchDeleteMediaOutput) {
	op := &request.Operation{
		Name:       opBatchDeleteMedia,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &BatchDeleteMediaInput{}
	}

	output = &BatchDeleteMediaOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// BatchDeleteMedia API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation BatchDeleteMedia for usage and error information.
func (c *KICKART) BatchDeleteMedia(input *BatchDeleteMediaInput) (*BatchDeleteMediaOutput, error) {
	req, out := c.BatchDeleteMediaRequest(input)
	return out, req.Send()
}

// BatchDeleteMediaWithContext is the same as BatchDeleteMedia with the addition of
// the ability to pass a context and additional request options.
//
// See BatchDeleteMedia for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) BatchDeleteMediaWithContext(ctx byteplus.Context, input *BatchDeleteMediaInput, opts ...request.Option) (*BatchDeleteMediaOutput, error) {
	req, out := c.BatchDeleteMediaRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type BatchDeleteMediaInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	ItemList []*string `type:"list"`
}

// String returns the string representation
func (s BatchDeleteMediaInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s BatchDeleteMediaInput) GoString() string {
	return s.String()
}

// SetItemList sets the ItemList field's value.
func (s *BatchDeleteMediaInput) SetItemList(v []*string) *BatchDeleteMediaInput {
	s.ItemList = v
	return s
}

type BatchDeleteMediaOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	Status *int32 `type:"int32" json:",omitempty"`
}

// String returns the string representation
func (s BatchDeleteMediaOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s BatchDeleteMediaOutput) GoString() string {
	return s.String()
}

// SetStatus sets the Status field's value.
func (s *BatchDeleteMediaOutput) SetStatus(v int32) *BatchDeleteMediaOutput {
	s.Status = &v
	return s
}
