// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opCreateMediaCommon = "CreateMedia"

// CreateMediaCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the CreateMediaCommon operation. The "output" return
// value will be populated with the CreateMediaCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned CreateMediaCommon Request to send the API call to the service.
// the "output" return value is not valid until after CreateMediaCommon Send returns without error.
//
// See CreateMediaCommon for more information on using the CreateMediaCommon
// API call, and error handling.
//
//    // Example sending a request using the CreateMediaCommonRequest method.
//    req, resp := client.CreateMediaCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) CreateMediaCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opCreateMediaCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// CreateMediaCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation CreateMediaCommon for usage and error information.
func (c *KICKART) CreateMediaCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.CreateMediaCommonRequest(input)
	return out, req.Send()
}

// CreateMediaCommonWithContext is the same as CreateMediaCommon with the addition of
// the ability to pass a context and additional request options.
//
// See CreateMediaCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) CreateMediaCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.CreateMediaCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opCreateMedia = "CreateMedia"

// CreateMediaRequest generates a "byteplus/request.Request" representing the
// client's request for the CreateMedia operation. The "output" return
// value will be populated with the CreateMediaCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned CreateMediaCommon Request to send the API call to the service.
// the "output" return value is not valid until after CreateMediaCommon Send returns without error.
//
// See CreateMedia for more information on using the CreateMedia
// API call, and error handling.
//
//    // Example sending a request using the CreateMediaRequest method.
//    req, resp := client.CreateMediaRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) CreateMediaRequest(input *CreateMediaInput) (req *request.Request, output *CreateMediaOutput) {
	op := &request.Operation{
		Name:       opCreateMedia,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &CreateMediaInput{}
	}

	output = &CreateMediaOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// CreateMedia API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation CreateMedia for usage and error information.
func (c *KICKART) CreateMedia(input *CreateMediaInput) (*CreateMediaOutput, error) {
	req, out := c.CreateMediaRequest(input)
	return out, req.Send()
}

// CreateMediaWithContext is the same as CreateMedia with the addition of
// the ability to pass a context and additional request options.
//
// See CreateMedia for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) CreateMediaWithContext(ctx byteplus.Context, input *CreateMediaInput, opts ...request.Option) (*CreateMediaOutput, error) {
	req, out := c.CreateMediaRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type CreateMediaInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	AspectRatio *string `type:"string" json:",omitempty"`

	Description *string `type:"string" json:",omitempty"`

	FolderId *int64 `type:"int64" json:",omitempty"`

	MediaExtension *string `type:"string" json:",omitempty"`

	NotSaveToAsset *bool `type:"boolean" json:",omitempty"`

	ResourceItem *string `type:"string" json:",omitempty"`

	ResourceType *string `type:"string" json:",omitempty"`

	Tags []*string `type:"list"`

	TeamSpaceId *int64 `type:"int64" json:",omitempty"`

	Title *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s CreateMediaInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateMediaInput) GoString() string {
	return s.String()
}

// SetAspectRatio sets the AspectRatio field's value.
func (s *CreateMediaInput) SetAspectRatio(v string) *CreateMediaInput {
	s.AspectRatio = &v
	return s
}

// SetDescription sets the Description field's value.
func (s *CreateMediaInput) SetDescription(v string) *CreateMediaInput {
	s.Description = &v
	return s
}

// SetFolderId sets the FolderId field's value.
func (s *CreateMediaInput) SetFolderId(v int64) *CreateMediaInput {
	s.FolderId = &v
	return s
}

// SetMediaExtension sets the MediaExtension field's value.
func (s *CreateMediaInput) SetMediaExtension(v string) *CreateMediaInput {
	s.MediaExtension = &v
	return s
}

// SetNotSaveToAsset sets the NotSaveToAsset field's value.
func (s *CreateMediaInput) SetNotSaveToAsset(v bool) *CreateMediaInput {
	s.NotSaveToAsset = &v
	return s
}

// SetResourceItem sets the ResourceItem field's value.
func (s *CreateMediaInput) SetResourceItem(v string) *CreateMediaInput {
	s.ResourceItem = &v
	return s
}

// SetResourceType sets the ResourceType field's value.
func (s *CreateMediaInput) SetResourceType(v string) *CreateMediaInput {
	s.ResourceType = &v
	return s
}

// SetTags sets the Tags field's value.
func (s *CreateMediaInput) SetTags(v []*string) *CreateMediaInput {
	s.Tags = v
	return s
}

// SetTeamSpaceId sets the TeamSpaceId field's value.
func (s *CreateMediaInput) SetTeamSpaceId(v int64) *CreateMediaInput {
	s.TeamSpaceId = &v
	return s
}

// SetTitle sets the Title field's value.
func (s *CreateMediaInput) SetTitle(v string) *CreateMediaInput {
	s.Title = &v
	return s
}

type CreateMediaOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	MediaId *string `type:"string" json:",omitempty"`

	MediaStoreId *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s CreateMediaOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateMediaOutput) GoString() string {
	return s.String()
}

// SetMediaId sets the MediaId field's value.
func (s *CreateMediaOutput) SetMediaId(v string) *CreateMediaOutput {
	s.MediaId = &v
	return s
}

// SetMediaStoreId sets the MediaStoreId field's value.
func (s *CreateMediaOutput) SetMediaStoreId(v string) *CreateMediaOutput {
	s.MediaStoreId = &v
	return s
}
