// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opUpdateFilmCommon = "UpdateFilm"

// UpdateFilmCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the UpdateFilmCommon operation. The "output" return
// value will be populated with the UpdateFilmCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned UpdateFilmCommon Request to send the API call to the service.
// the "output" return value is not valid until after UpdateFilmCommon Send returns without error.
//
// See UpdateFilmCommon for more information on using the UpdateFilmCommon
// API call, and error handling.
//
//    // Example sending a request using the UpdateFilmCommonRequest method.
//    req, resp := client.UpdateFilmCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) UpdateFilmCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opUpdateFilmCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// UpdateFilmCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation UpdateFilmCommon for usage and error information.
func (c *KICKART) UpdateFilmCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.UpdateFilmCommonRequest(input)
	return out, req.Send()
}

// UpdateFilmCommonWithContext is the same as UpdateFilmCommon with the addition of
// the ability to pass a context and additional request options.
//
// See UpdateFilmCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) UpdateFilmCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.UpdateFilmCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opUpdateFilm = "UpdateFilm"

// UpdateFilmRequest generates a "byteplus/request.Request" representing the
// client's request for the UpdateFilm operation. The "output" return
// value will be populated with the UpdateFilmCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned UpdateFilmCommon Request to send the API call to the service.
// the "output" return value is not valid until after UpdateFilmCommon Send returns without error.
//
// See UpdateFilm for more information on using the UpdateFilm
// API call, and error handling.
//
//    // Example sending a request using the UpdateFilmRequest method.
//    req, resp := client.UpdateFilmRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) UpdateFilmRequest(input *UpdateFilmInput) (req *request.Request, output *UpdateFilmOutput) {
	op := &request.Operation{
		Name:       opUpdateFilm,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &UpdateFilmInput{}
	}

	output = &UpdateFilmOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// UpdateFilm API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation UpdateFilm for usage and error information.
func (c *KICKART) UpdateFilm(input *UpdateFilmInput) (*UpdateFilmOutput, error) {
	req, out := c.UpdateFilmRequest(input)
	return out, req.Send()
}

// UpdateFilmWithContext is the same as UpdateFilm with the addition of
// the ability to pass a context and additional request options.
//
// See UpdateFilm for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) UpdateFilmWithContext(ctx byteplus.Context, input *UpdateFilmInput, opts ...request.Option) (*UpdateFilmOutput, error) {
	req, out := c.UpdateFilmRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type UpdateFilmInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	ClientExtraInfo *string `type:"string" json:",omitempty"`

	CopyrightStatus *int32 `type:"int32" json:",omitempty"`

	Description *string `type:"string" json:",omitempty"`

	Duration *int32 `type:"int32" json:",omitempty"`

	MediaId *string `type:"string" json:",omitempty"`

	NleData *string `type:"string" json:",omitempty"`

	SectionData *string `type:"string" json:",omitempty"`

	SourceFrom *string `type:"string" json:",omitempty"`

	StoreId *string `type:"string" json:",omitempty"`

	Tags []*string `type:"list"`

	Title *string `type:"string" json:",omitempty"`

	UpdateResources []*string `type:"list"`

	UserdefinedCategory []*string `type:"list"`
}

// String returns the string representation
func (s UpdateFilmInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s UpdateFilmInput) GoString() string {
	return s.String()
}

// SetClientExtraInfo sets the ClientExtraInfo field's value.
func (s *UpdateFilmInput) SetClientExtraInfo(v string) *UpdateFilmInput {
	s.ClientExtraInfo = &v
	return s
}

// SetCopyrightStatus sets the CopyrightStatus field's value.
func (s *UpdateFilmInput) SetCopyrightStatus(v int32) *UpdateFilmInput {
	s.CopyrightStatus = &v
	return s
}

// SetDescription sets the Description field's value.
func (s *UpdateFilmInput) SetDescription(v string) *UpdateFilmInput {
	s.Description = &v
	return s
}

// SetDuration sets the Duration field's value.
func (s *UpdateFilmInput) SetDuration(v int32) *UpdateFilmInput {
	s.Duration = &v
	return s
}

// SetMediaId sets the MediaId field's value.
func (s *UpdateFilmInput) SetMediaId(v string) *UpdateFilmInput {
	s.MediaId = &v
	return s
}

// SetNleData sets the NleData field's value.
func (s *UpdateFilmInput) SetNleData(v string) *UpdateFilmInput {
	s.NleData = &v
	return s
}

// SetSectionData sets the SectionData field's value.
func (s *UpdateFilmInput) SetSectionData(v string) *UpdateFilmInput {
	s.SectionData = &v
	return s
}

// SetSourceFrom sets the SourceFrom field's value.
func (s *UpdateFilmInput) SetSourceFrom(v string) *UpdateFilmInput {
	s.SourceFrom = &v
	return s
}

// SetStoreId sets the StoreId field's value.
func (s *UpdateFilmInput) SetStoreId(v string) *UpdateFilmInput {
	s.StoreId = &v
	return s
}

// SetTags sets the Tags field's value.
func (s *UpdateFilmInput) SetTags(v []*string) *UpdateFilmInput {
	s.Tags = v
	return s
}

// SetTitle sets the Title field's value.
func (s *UpdateFilmInput) SetTitle(v string) *UpdateFilmInput {
	s.Title = &v
	return s
}

// SetUpdateResources sets the UpdateResources field's value.
func (s *UpdateFilmInput) SetUpdateResources(v []*string) *UpdateFilmInput {
	s.UpdateResources = v
	return s
}

// SetUserdefinedCategory sets the UserdefinedCategory field's value.
func (s *UpdateFilmInput) SetUserdefinedCategory(v []*string) *UpdateFilmInput {
	s.UserdefinedCategory = v
	return s
}

type UpdateFilmOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata
}

// String returns the string representation
func (s UpdateFilmOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s UpdateFilmOutput) GoString() string {
	return s.String()
}
