// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opDeleteAllTaskItemCommon = "DeleteAllTaskItem"

// DeleteAllTaskItemCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the DeleteAllTaskItemCommon operation. The "output" return
// value will be populated with the DeleteAllTaskItemCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DeleteAllTaskItemCommon Request to send the API call to the service.
// the "output" return value is not valid until after DeleteAllTaskItemCommon Send returns without error.
//
// See DeleteAllTaskItemCommon for more information on using the DeleteAllTaskItemCommon
// API call, and error handling.
//
//    // Example sending a request using the DeleteAllTaskItemCommonRequest method.
//    req, resp := client.DeleteAllTaskItemCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) DeleteAllTaskItemCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opDeleteAllTaskItemCommon,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	return
}

// DeleteAllTaskItemCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation DeleteAllTaskItemCommon for usage and error information.
func (c *KICKART) DeleteAllTaskItemCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.DeleteAllTaskItemCommonRequest(input)
	return out, req.Send()
}

// DeleteAllTaskItemCommonWithContext is the same as DeleteAllTaskItemCommon with the addition of
// the ability to pass a context and additional request options.
//
// See DeleteAllTaskItemCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) DeleteAllTaskItemCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.DeleteAllTaskItemCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opDeleteAllTaskItem = "DeleteAllTaskItem"

// DeleteAllTaskItemRequest generates a "byteplus/request.Request" representing the
// client's request for the DeleteAllTaskItem operation. The "output" return
// value will be populated with the DeleteAllTaskItemCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned DeleteAllTaskItemCommon Request to send the API call to the service.
// the "output" return value is not valid until after DeleteAllTaskItemCommon Send returns without error.
//
// See DeleteAllTaskItem for more information on using the DeleteAllTaskItem
// API call, and error handling.
//
//    // Example sending a request using the DeleteAllTaskItemRequest method.
//    req, resp := client.DeleteAllTaskItemRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) DeleteAllTaskItemRequest(input *DeleteAllTaskItemInput) (req *request.Request, output *DeleteAllTaskItemOutput) {
	op := &request.Operation{
		Name:       opDeleteAllTaskItem,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DeleteAllTaskItemInput{}
	}

	output = &DeleteAllTaskItemOutput{}
	req = c.newRequest(op, input, output)

	return
}

// DeleteAllTaskItem API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation DeleteAllTaskItem for usage and error information.
func (c *KICKART) DeleteAllTaskItem(input *DeleteAllTaskItemInput) (*DeleteAllTaskItemOutput, error) {
	req, out := c.DeleteAllTaskItemRequest(input)
	return out, req.Send()
}

// DeleteAllTaskItemWithContext is the same as DeleteAllTaskItem with the addition of
// the ability to pass a context and additional request options.
//
// See DeleteAllTaskItem for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) DeleteAllTaskItemWithContext(ctx byteplus.Context, input *DeleteAllTaskItemInput, opts ...request.Option) (*DeleteAllTaskItemOutput, error) {
	req, out := c.DeleteAllTaskItemRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type DeleteAllTaskItemInput struct {
	_ struct{} `type:"structure"`

	// Id is a required field
	Id *string `type:"string" required:"true"`
}

// String returns the string representation
func (s DeleteAllTaskItemInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteAllTaskItemInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *DeleteAllTaskItemInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "DeleteAllTaskItemInput"}
	if s.Id == nil {
		invalidParams.Add(request.NewErrParamRequired("Id"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetId sets the Id field's value.
func (s *DeleteAllTaskItemInput) SetId(v string) *DeleteAllTaskItemInput {
	s.Id = &v
	return s
}

type DeleteAllTaskItemOutput struct {
	_ struct{} `type:"structure"`

	Metadata *response.ResponseMetadata
}

// String returns the string representation
func (s DeleteAllTaskItemOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteAllTaskItemOutput) GoString() string {
	return s.String()
}
