// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opGenAdVariationsVideoCommon = "GenAdVariationsVideo"

// GenAdVariationsVideoCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the GenAdVariationsVideoCommon operation. The "output" return
// value will be populated with the GenAdVariationsVideoCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GenAdVariationsVideoCommon Request to send the API call to the service.
// the "output" return value is not valid until after GenAdVariationsVideoCommon Send returns without error.
//
// See GenAdVariationsVideoCommon for more information on using the GenAdVariationsVideoCommon
// API call, and error handling.
//
//    // Example sending a request using the GenAdVariationsVideoCommonRequest method.
//    req, resp := client.GenAdVariationsVideoCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GenAdVariationsVideoCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opGenAdVariationsVideoCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GenAdVariationsVideoCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GenAdVariationsVideoCommon for usage and error information.
func (c *KICKART) GenAdVariationsVideoCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.GenAdVariationsVideoCommonRequest(input)
	return out, req.Send()
}

// GenAdVariationsVideoCommonWithContext is the same as GenAdVariationsVideoCommon with the addition of
// the ability to pass a context and additional request options.
//
// See GenAdVariationsVideoCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GenAdVariationsVideoCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.GenAdVariationsVideoCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opGenAdVariationsVideo = "GenAdVariationsVideo"

// GenAdVariationsVideoRequest generates a "byteplus/request.Request" representing the
// client's request for the GenAdVariationsVideo operation. The "output" return
// value will be populated with the GenAdVariationsVideoCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GenAdVariationsVideoCommon Request to send the API call to the service.
// the "output" return value is not valid until after GenAdVariationsVideoCommon Send returns without error.
//
// See GenAdVariationsVideo for more information on using the GenAdVariationsVideo
// API call, and error handling.
//
//    // Example sending a request using the GenAdVariationsVideoRequest method.
//    req, resp := client.GenAdVariationsVideoRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GenAdVariationsVideoRequest(input *GenAdVariationsVideoInput) (req *request.Request, output *GenAdVariationsVideoOutput) {
	op := &request.Operation{
		Name:       opGenAdVariationsVideo,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GenAdVariationsVideoInput{}
	}

	output = &GenAdVariationsVideoOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GenAdVariationsVideo API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GenAdVariationsVideo for usage and error information.
func (c *KICKART) GenAdVariationsVideo(input *GenAdVariationsVideoInput) (*GenAdVariationsVideoOutput, error) {
	req, out := c.GenAdVariationsVideoRequest(input)
	return out, req.Send()
}

// GenAdVariationsVideoWithContext is the same as GenAdVariationsVideo with the addition of
// the ability to pass a context and additional request options.
//
// See GenAdVariationsVideo for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GenAdVariationsVideoWithContext(ctx byteplus.Context, input *GenAdVariationsVideoInput, opts ...request.Option) (*GenAdVariationsVideoOutput, error) {
	req, out := c.GenAdVariationsVideoRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type GenAdVariationsVideoInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	// CompositionId is a required field
	CompositionId *string `type:"string" json:",omitempty" required:"true"`
}

// String returns the string representation
func (s GenAdVariationsVideoInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GenAdVariationsVideoInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *GenAdVariationsVideoInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "GenAdVariationsVideoInput"}
	if s.CompositionId == nil {
		invalidParams.Add(request.NewErrParamRequired("CompositionId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetCompositionId sets the CompositionId field's value.
func (s *GenAdVariationsVideoInput) SetCompositionId(v string) *GenAdVariationsVideoInput {
	s.CompositionId = &v
	return s
}

type GenAdVariationsVideoOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	TaskId *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s GenAdVariationsVideoOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GenAdVariationsVideoOutput) GoString() string {
	return s.String()
}

// SetTaskId sets the TaskId field's value.
func (s *GenAdVariationsVideoOutput) SetTaskId(v string) *GenAdVariationsVideoOutput {
	s.TaskId = &v
	return s
}
