// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opValidateAvatarImageCommon = "ValidateAvatarImage"

// ValidateAvatarImageCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the ValidateAvatarImageCommon operation. The "output" return
// value will be populated with the ValidateAvatarImageCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ValidateAvatarImageCommon Request to send the API call to the service.
// the "output" return value is not valid until after ValidateAvatarImageCommon Send returns without error.
//
// See ValidateAvatarImageCommon for more information on using the ValidateAvatarImageCommon
// API call, and error handling.
//
//    // Example sending a request using the ValidateAvatarImageCommonRequest method.
//    req, resp := client.ValidateAvatarImageCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) ValidateAvatarImageCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opValidateAvatarImageCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ValidateAvatarImageCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation ValidateAvatarImageCommon for usage and error information.
func (c *KICKART) ValidateAvatarImageCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.ValidateAvatarImageCommonRequest(input)
	return out, req.Send()
}

// ValidateAvatarImageCommonWithContext is the same as ValidateAvatarImageCommon with the addition of
// the ability to pass a context and additional request options.
//
// See ValidateAvatarImageCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) ValidateAvatarImageCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.ValidateAvatarImageCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opValidateAvatarImage = "ValidateAvatarImage"

// ValidateAvatarImageRequest generates a "byteplus/request.Request" representing the
// client's request for the ValidateAvatarImage operation. The "output" return
// value will be populated with the ValidateAvatarImageCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ValidateAvatarImageCommon Request to send the API call to the service.
// the "output" return value is not valid until after ValidateAvatarImageCommon Send returns without error.
//
// See ValidateAvatarImage for more information on using the ValidateAvatarImage
// API call, and error handling.
//
//    // Example sending a request using the ValidateAvatarImageRequest method.
//    req, resp := client.ValidateAvatarImageRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) ValidateAvatarImageRequest(input *ValidateAvatarImageInput) (req *request.Request, output *ValidateAvatarImageOutput) {
	op := &request.Operation{
		Name:       opValidateAvatarImage,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ValidateAvatarImageInput{}
	}

	output = &ValidateAvatarImageOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ValidateAvatarImage API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation ValidateAvatarImage for usage and error information.
func (c *KICKART) ValidateAvatarImage(input *ValidateAvatarImageInput) (*ValidateAvatarImageOutput, error) {
	req, out := c.ValidateAvatarImageRequest(input)
	return out, req.Send()
}

// ValidateAvatarImageWithContext is the same as ValidateAvatarImage with the addition of
// the ability to pass a context and additional request options.
//
// See ValidateAvatarImage for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) ValidateAvatarImageWithContext(ctx byteplus.Context, input *ValidateAvatarImageInput, opts ...request.Option) (*ValidateAvatarImageOutput, error) {
	req, out := c.ValidateAvatarImageRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type ValidateAvatarImageInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	MediaId *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ValidateAvatarImageInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ValidateAvatarImageInput) GoString() string {
	return s.String()
}

// SetMediaId sets the MediaId field's value.
func (s *ValidateAvatarImageInput) SetMediaId(v string) *ValidateAvatarImageInput {
	s.MediaId = &v
	return s
}

type ValidateAvatarImageOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	ErrorCode *int32 `type:"int32" json:",omitempty"`

	IsValid *bool `type:"boolean" json:",omitempty"`
}

// String returns the string representation
func (s ValidateAvatarImageOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ValidateAvatarImageOutput) GoString() string {
	return s.String()
}

// SetErrorCode sets the ErrorCode field's value.
func (s *ValidateAvatarImageOutput) SetErrorCode(v int32) *ValidateAvatarImageOutput {
	s.ErrorCode = &v
	return s
}

// SetIsValid sets the IsValid field's value.
func (s *ValidateAvatarImageOutput) SetIsValid(v bool) *ValidateAvatarImageOutput {
	s.IsValid = &v
	return s
}
