// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opListTasksCommon = "ListTasks"

// ListTasksCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the ListTasksCommon operation. The "output" return
// value will be populated with the ListTasksCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ListTasksCommon Request to send the API call to the service.
// the "output" return value is not valid until after ListTasksCommon Send returns without error.
//
// See ListTasksCommon for more information on using the ListTasksCommon
// API call, and error handling.
//
//    // Example sending a request using the ListTasksCommonRequest method.
//    req, resp := client.ListTasksCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) ListTasksCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opListTasksCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ListTasksCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation ListTasksCommon for usage and error information.
func (c *KICKART) ListTasksCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.ListTasksCommonRequest(input)
	return out, req.Send()
}

// ListTasksCommonWithContext is the same as ListTasksCommon with the addition of
// the ability to pass a context and additional request options.
//
// See ListTasksCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) ListTasksCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.ListTasksCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opListTasks = "ListTasks"

// ListTasksRequest generates a "byteplus/request.Request" representing the
// client's request for the ListTasks operation. The "output" return
// value will be populated with the ListTasksCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ListTasksCommon Request to send the API call to the service.
// the "output" return value is not valid until after ListTasksCommon Send returns without error.
//
// See ListTasks for more information on using the ListTasks
// API call, and error handling.
//
//    // Example sending a request using the ListTasksRequest method.
//    req, resp := client.ListTasksRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) ListTasksRequest(input *ListTasksInput) (req *request.Request, output *ListTasksOutput) {
	op := &request.Operation{
		Name:       opListTasks,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ListTasksInput{}
	}

	output = &ListTasksOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ListTasks API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation ListTasks for usage and error information.
func (c *KICKART) ListTasks(input *ListTasksInput) (*ListTasksOutput, error) {
	req, out := c.ListTasksRequest(input)
	return out, req.Send()
}

// ListTasksWithContext is the same as ListTasks with the addition of
// the ability to pass a context and additional request options.
//
// See ListTasks for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) ListTasksWithContext(ctx byteplus.Context, input *ListTasksInput, opts ...request.Option) (*ListTasksOutput, error) {
	req, out := c.ListTasksRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type ListTasksInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	// PageNum is a required field
	PageNum *int32 `type:"int32" json:",omitempty" required:"true"`

	// PageSize is a required field
	PageSize *int32 `type:"int32" json:",omitempty" required:"true"`

	TmplIds []*string `type:"list"`
}

// String returns the string representation
func (s ListTasksInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ListTasksInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *ListTasksInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "ListTasksInput"}
	if s.PageNum == nil {
		invalidParams.Add(request.NewErrParamRequired("PageNum"))
	}
	if s.PageSize == nil {
		invalidParams.Add(request.NewErrParamRequired("PageSize"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetPageNum sets the PageNum field's value.
func (s *ListTasksInput) SetPageNum(v int32) *ListTasksInput {
	s.PageNum = &v
	return s
}

// SetPageSize sets the PageSize field's value.
func (s *ListTasksInput) SetPageSize(v int32) *ListTasksInput {
	s.PageSize = &v
	return s
}

// SetTmplIds sets the TmplIds field's value.
func (s *ListTasksInput) SetTmplIds(v []*string) *ListTasksInput {
	s.TmplIds = v
	return s
}

type ListTasksOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	Extra *string `type:"string" json:",omitempty"`

	List []*string `type:"list"`

	PageInfo *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ListTasksOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ListTasksOutput) GoString() string {
	return s.String()
}

// SetExtra sets the Extra field's value.
func (s *ListTasksOutput) SetExtra(v string) *ListTasksOutput {
	s.Extra = &v
	return s
}

// SetList sets the List field's value.
func (s *ListTasksOutput) SetList(v []*string) *ListTasksOutput {
	s.List = v
	return s
}

// SetPageInfo sets the PageInfo field's value.
func (s *ListTasksOutput) SetPageInfo(v string) *ListTasksOutput {
	s.PageInfo = &v
	return s
}
