// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opGenPicsVideoByStoryCommon = "GenPicsVideoByStory"

// GenPicsVideoByStoryCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the GenPicsVideoByStoryCommon operation. The "output" return
// value will be populated with the GenPicsVideoByStoryCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GenPicsVideoByStoryCommon Request to send the API call to the service.
// the "output" return value is not valid until after GenPicsVideoByStoryCommon Send returns without error.
//
// See GenPicsVideoByStoryCommon for more information on using the GenPicsVideoByStoryCommon
// API call, and error handling.
//
//    // Example sending a request using the GenPicsVideoByStoryCommonRequest method.
//    req, resp := client.GenPicsVideoByStoryCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GenPicsVideoByStoryCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opGenPicsVideoByStoryCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GenPicsVideoByStoryCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GenPicsVideoByStoryCommon for usage and error information.
func (c *KICKART) GenPicsVideoByStoryCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.GenPicsVideoByStoryCommonRequest(input)
	return out, req.Send()
}

// GenPicsVideoByStoryCommonWithContext is the same as GenPicsVideoByStoryCommon with the addition of
// the ability to pass a context and additional request options.
//
// See GenPicsVideoByStoryCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GenPicsVideoByStoryCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.GenPicsVideoByStoryCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opGenPicsVideoByStory = "GenPicsVideoByStory"

// GenPicsVideoByStoryRequest generates a "byteplus/request.Request" representing the
// client's request for the GenPicsVideoByStory operation. The "output" return
// value will be populated with the GenPicsVideoByStoryCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GenPicsVideoByStoryCommon Request to send the API call to the service.
// the "output" return value is not valid until after GenPicsVideoByStoryCommon Send returns without error.
//
// See GenPicsVideoByStory for more information on using the GenPicsVideoByStory
// API call, and error handling.
//
//    // Example sending a request using the GenPicsVideoByStoryRequest method.
//    req, resp := client.GenPicsVideoByStoryRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GenPicsVideoByStoryRequest(input *GenPicsVideoByStoryInput) (req *request.Request, output *GenPicsVideoByStoryOutput) {
	op := &request.Operation{
		Name:       opGenPicsVideoByStory,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GenPicsVideoByStoryInput{}
	}

	output = &GenPicsVideoByStoryOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GenPicsVideoByStory API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GenPicsVideoByStory for usage and error information.
func (c *KICKART) GenPicsVideoByStory(input *GenPicsVideoByStoryInput) (*GenPicsVideoByStoryOutput, error) {
	req, out := c.GenPicsVideoByStoryRequest(input)
	return out, req.Send()
}

// GenPicsVideoByStoryWithContext is the same as GenPicsVideoByStory with the addition of
// the ability to pass a context and additional request options.
//
// See GenPicsVideoByStory for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GenPicsVideoByStoryWithContext(ctx byteplus.Context, input *GenPicsVideoByStoryInput, opts ...request.Option) (*GenPicsVideoByStoryOutput, error) {
	req, out := c.GenPicsVideoByStoryRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type GenPicsVideoByStoryInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	CompositionId *string `type:"string" json:",omitempty"`

	Lang *string `type:"string" json:",omitempty"`

	SceneId *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s GenPicsVideoByStoryInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GenPicsVideoByStoryInput) GoString() string {
	return s.String()
}

// SetCompositionId sets the CompositionId field's value.
func (s *GenPicsVideoByStoryInput) SetCompositionId(v string) *GenPicsVideoByStoryInput {
	s.CompositionId = &v
	return s
}

// SetLang sets the Lang field's value.
func (s *GenPicsVideoByStoryInput) SetLang(v string) *GenPicsVideoByStoryInput {
	s.Lang = &v
	return s
}

// SetSceneId sets the SceneId field's value.
func (s *GenPicsVideoByStoryInput) SetSceneId(v string) *GenPicsVideoByStoryInput {
	s.SceneId = &v
	return s
}

type GenPicsVideoByStoryOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	TaskId *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s GenPicsVideoByStoryOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GenPicsVideoByStoryOutput) GoString() string {
	return s.String()
}

// SetTaskId sets the TaskId field's value.
func (s *GenPicsVideoByStoryOutput) SetTaskId(v string) *GenPicsVideoByStoryOutput {
	s.TaskId = &v
	return s
}
