// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opGetCategoryDetailCommon = "GetCategoryDetail"

// GetCategoryDetailCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the GetCategoryDetailCommon operation. The "output" return
// value will be populated with the GetCategoryDetailCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetCategoryDetailCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetCategoryDetailCommon Send returns without error.
//
// See GetCategoryDetailCommon for more information on using the GetCategoryDetailCommon
// API call, and error handling.
//
//    // Example sending a request using the GetCategoryDetailCommonRequest method.
//    req, resp := client.GetCategoryDetailCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetCategoryDetailCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opGetCategoryDetailCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetCategoryDetailCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetCategoryDetailCommon for usage and error information.
func (c *KICKART) GetCategoryDetailCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.GetCategoryDetailCommonRequest(input)
	return out, req.Send()
}

// GetCategoryDetailCommonWithContext is the same as GetCategoryDetailCommon with the addition of
// the ability to pass a context and additional request options.
//
// See GetCategoryDetailCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetCategoryDetailCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.GetCategoryDetailCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opGetCategoryDetail = "GetCategoryDetail"

// GetCategoryDetailRequest generates a "byteplus/request.Request" representing the
// client's request for the GetCategoryDetail operation. The "output" return
// value will be populated with the GetCategoryDetailCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetCategoryDetailCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetCategoryDetailCommon Send returns without error.
//
// See GetCategoryDetail for more information on using the GetCategoryDetail
// API call, and error handling.
//
//    // Example sending a request using the GetCategoryDetailRequest method.
//    req, resp := client.GetCategoryDetailRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetCategoryDetailRequest(input *GetCategoryDetailInput) (req *request.Request, output *GetCategoryDetailOutput) {
	op := &request.Operation{
		Name:       opGetCategoryDetail,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GetCategoryDetailInput{}
	}

	output = &GetCategoryDetailOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetCategoryDetail API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetCategoryDetail for usage and error information.
func (c *KICKART) GetCategoryDetail(input *GetCategoryDetailInput) (*GetCategoryDetailOutput, error) {
	req, out := c.GetCategoryDetailRequest(input)
	return out, req.Send()
}

// GetCategoryDetailWithContext is the same as GetCategoryDetail with the addition of
// the ability to pass a context and additional request options.
//
// See GetCategoryDetail for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetCategoryDetailWithContext(ctx byteplus.Context, input *GetCategoryDetailInput, opts ...request.Option) (*GetCategoryDetailOutput, error) {
	req, out := c.GetCategoryDetailRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type GetCategoryDetailInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	BizId *string `type:"string" json:",omitempty"`

	CategoryCode *string `type:"string" json:",omitempty"`

	Lang *string `type:"string" json:",omitempty"`

	PanelId *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s GetCategoryDetailInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetCategoryDetailInput) GoString() string {
	return s.String()
}

// SetBizId sets the BizId field's value.
func (s *GetCategoryDetailInput) SetBizId(v string) *GetCategoryDetailInput {
	s.BizId = &v
	return s
}

// SetCategoryCode sets the CategoryCode field's value.
func (s *GetCategoryDetailInput) SetCategoryCode(v string) *GetCategoryDetailInput {
	s.CategoryCode = &v
	return s
}

// SetLang sets the Lang field's value.
func (s *GetCategoryDetailInput) SetLang(v string) *GetCategoryDetailInput {
	s.Lang = &v
	return s
}

// SetPanelId sets the PanelId field's value.
func (s *GetCategoryDetailInput) SetPanelId(v string) *GetCategoryDetailInput {
	s.PanelId = &v
	return s
}

type GetCategoryDetailOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	CategoryDetails []*string `type:"list"`
}

// String returns the string representation
func (s GetCategoryDetailOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetCategoryDetailOutput) GoString() string {
	return s.String()
}

// SetCategoryDetails sets the CategoryDetails field's value.
func (s *GetCategoryDetailOutput) SetCategoryDetails(v []*string) *GetCategoryDetailOutput {
	s.CategoryDetails = v
	return s
}
