// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opCheckDeleteMediaCommon = "CheckDeleteMedia"

// CheckDeleteMediaCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the CheckDeleteMediaCommon operation. The "output" return
// value will be populated with the CheckDeleteMediaCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned CheckDeleteMediaCommon Request to send the API call to the service.
// the "output" return value is not valid until after CheckDeleteMediaCommon Send returns without error.
//
// See CheckDeleteMediaCommon for more information on using the CheckDeleteMediaCommon
// API call, and error handling.
//
//    // Example sending a request using the CheckDeleteMediaCommonRequest method.
//    req, resp := client.CheckDeleteMediaCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) CheckDeleteMediaCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opCheckDeleteMediaCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// CheckDeleteMediaCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation CheckDeleteMediaCommon for usage and error information.
func (c *KICKART) CheckDeleteMediaCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.CheckDeleteMediaCommonRequest(input)
	return out, req.Send()
}

// CheckDeleteMediaCommonWithContext is the same as CheckDeleteMediaCommon with the addition of
// the ability to pass a context and additional request options.
//
// See CheckDeleteMediaCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) CheckDeleteMediaCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.CheckDeleteMediaCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opCheckDeleteMedia = "CheckDeleteMedia"

// CheckDeleteMediaRequest generates a "byteplus/request.Request" representing the
// client's request for the CheckDeleteMedia operation. The "output" return
// value will be populated with the CheckDeleteMediaCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned CheckDeleteMediaCommon Request to send the API call to the service.
// the "output" return value is not valid until after CheckDeleteMediaCommon Send returns without error.
//
// See CheckDeleteMedia for more information on using the CheckDeleteMedia
// API call, and error handling.
//
//    // Example sending a request using the CheckDeleteMediaRequest method.
//    req, resp := client.CheckDeleteMediaRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) CheckDeleteMediaRequest(input *CheckDeleteMediaInput) (req *request.Request, output *CheckDeleteMediaOutput) {
	op := &request.Operation{
		Name:       opCheckDeleteMedia,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &CheckDeleteMediaInput{}
	}

	output = &CheckDeleteMediaOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// CheckDeleteMedia API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation CheckDeleteMedia for usage and error information.
func (c *KICKART) CheckDeleteMedia(input *CheckDeleteMediaInput) (*CheckDeleteMediaOutput, error) {
	req, out := c.CheckDeleteMediaRequest(input)
	return out, req.Send()
}

// CheckDeleteMediaWithContext is the same as CheckDeleteMedia with the addition of
// the ability to pass a context and additional request options.
//
// See CheckDeleteMedia for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) CheckDeleteMediaWithContext(ctx byteplus.Context, input *CheckDeleteMediaInput, opts ...request.Option) (*CheckDeleteMediaOutput, error) {
	req, out := c.CheckDeleteMediaRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type CheckDeleteMediaInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	ItemList []*string `type:"list"`
}

// String returns the string representation
func (s CheckDeleteMediaInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s CheckDeleteMediaInput) GoString() string {
	return s.String()
}

// SetItemList sets the ItemList field's value.
func (s *CheckDeleteMediaInput) SetItemList(v []*string) *CheckDeleteMediaInput {
	s.ItemList = v
	return s
}

type CheckDeleteMediaOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	InUse *bool `type:"boolean" json:",omitempty"`
}

// String returns the string representation
func (s CheckDeleteMediaOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s CheckDeleteMediaOutput) GoString() string {
	return s.String()
}

// SetInUse sets the InUse field's value.
func (s *CheckDeleteMediaOutput) SetInUse(v bool) *CheckDeleteMediaOutput {
	s.InUse = &v
	return s
}
