// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opExportVideoCommon = "ExportVideo"

// ExportVideoCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the ExportVideoCommon operation. The "output" return
// value will be populated with the ExportVideoCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ExportVideoCommon Request to send the API call to the service.
// the "output" return value is not valid until after ExportVideoCommon Send returns without error.
//
// See ExportVideoCommon for more information on using the ExportVideoCommon
// API call, and error handling.
//
//    // Example sending a request using the ExportVideoCommonRequest method.
//    req, resp := client.ExportVideoCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) ExportVideoCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opExportVideoCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ExportVideoCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation ExportVideoCommon for usage and error information.
func (c *KICKART) ExportVideoCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.ExportVideoCommonRequest(input)
	return out, req.Send()
}

// ExportVideoCommonWithContext is the same as ExportVideoCommon with the addition of
// the ability to pass a context and additional request options.
//
// See ExportVideoCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) ExportVideoCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.ExportVideoCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opExportVideo = "ExportVideo"

// ExportVideoRequest generates a "byteplus/request.Request" representing the
// client's request for the ExportVideo operation. The "output" return
// value will be populated with the ExportVideoCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ExportVideoCommon Request to send the API call to the service.
// the "output" return value is not valid until after ExportVideoCommon Send returns without error.
//
// See ExportVideo for more information on using the ExportVideo
// API call, and error handling.
//
//    // Example sending a request using the ExportVideoRequest method.
//    req, resp := client.ExportVideoRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) ExportVideoRequest(input *ExportVideoInput) (req *request.Request, output *ExportVideoOutput) {
	op := &request.Operation{
		Name:       opExportVideo,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ExportVideoInput{}
	}

	output = &ExportVideoOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// ExportVideo API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation ExportVideo for usage and error information.
func (c *KICKART) ExportVideo(input *ExportVideoInput) (*ExportVideoOutput, error) {
	req, out := c.ExportVideoRequest(input)
	return out, req.Send()
}

// ExportVideoWithContext is the same as ExportVideo with the addition of
// the ability to pass a context and additional request options.
//
// See ExportVideo for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) ExportVideoWithContext(ctx byteplus.Context, input *ExportVideoInput, opts ...request.Option) (*ExportVideoOutput, error) {
	req, out := c.ExportVideoRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type ExportVideoInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	CompositionId *string `type:"string" json:",omitempty"`

	DraftIndex *int32 `type:"int32" json:",omitempty"`
}

// String returns the string representation
func (s ExportVideoInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ExportVideoInput) GoString() string {
	return s.String()
}

// SetCompositionId sets the CompositionId field's value.
func (s *ExportVideoInput) SetCompositionId(v string) *ExportVideoInput {
	s.CompositionId = &v
	return s
}

// SetDraftIndex sets the DraftIndex field's value.
func (s *ExportVideoInput) SetDraftIndex(v int32) *ExportVideoInput {
	s.DraftIndex = &v
	return s
}

type ExportVideoOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	TaskId *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ExportVideoOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ExportVideoOutput) GoString() string {
	return s.String()
}

// SetTaskId sets the TaskId field's value.
func (s *ExportVideoOutput) SetTaskId(v string) *ExportVideoOutput {
	s.TaskId = &v
	return s
}
