// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opGetDraftCommon = "GetDraft"

// GetDraftCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the GetDraftCommon operation. The "output" return
// value will be populated with the GetDraftCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetDraftCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetDraftCommon Send returns without error.
//
// See GetDraftCommon for more information on using the GetDraftCommon
// API call, and error handling.
//
//    // Example sending a request using the GetDraftCommonRequest method.
//    req, resp := client.GetDraftCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetDraftCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opGetDraftCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetDraftCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetDraftCommon for usage and error information.
func (c *KICKART) GetDraftCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.GetDraftCommonRequest(input)
	return out, req.Send()
}

// GetDraftCommonWithContext is the same as GetDraftCommon with the addition of
// the ability to pass a context and additional request options.
//
// See GetDraftCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetDraftCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.GetDraftCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opGetDraft = "GetDraft"

// GetDraftRequest generates a "byteplus/request.Request" representing the
// client's request for the GetDraft operation. The "output" return
// value will be populated with the GetDraftCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned GetDraftCommon Request to send the API call to the service.
// the "output" return value is not valid until after GetDraftCommon Send returns without error.
//
// See GetDraft for more information on using the GetDraft
// API call, and error handling.
//
//    // Example sending a request using the GetDraftRequest method.
//    req, resp := client.GetDraftRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) GetDraftRequest(input *GetDraftInput) (req *request.Request, output *GetDraftOutput) {
	op := &request.Operation{
		Name:       opGetDraft,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GetDraftInput{}
	}

	output = &GetDraftOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// GetDraft API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation GetDraft for usage and error information.
func (c *KICKART) GetDraft(input *GetDraftInput) (*GetDraftOutput, error) {
	req, out := c.GetDraftRequest(input)
	return out, req.Send()
}

// GetDraftWithContext is the same as GetDraft with the addition of
// the ability to pass a context and additional request options.
//
// See GetDraft for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) GetDraftWithContext(ctx byteplus.Context, input *GetDraftInput, opts ...request.Option) (*GetDraftOutput, error) {
	req, out := c.GetDraftRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type GetDraftInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	DraftIds []*int64 `type:"list"`
}

// String returns the string representation
func (s GetDraftInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetDraftInput) GoString() string {
	return s.String()
}

// SetDraftIds sets the DraftIds field's value.
func (s *GetDraftInput) SetDraftIds(v []*int64) *GetDraftInput {
	s.DraftIds = v
	return s
}

type GetDraftOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	MediaId *int64 `type:"int64" json:",omitempty"`
}

// String returns the string representation
func (s GetDraftOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s GetDraftOutput) GoString() string {
	return s.String()
}

// SetMediaId sets the MediaId field's value.
func (s *GetDraftOutput) SetMediaId(v int64) *GetDraftOutput {
	s.MediaId = &v
	return s
}
