// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package kickart

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opQueryCreativePointLogsCommon = "QueryCreativePointLogs"

// QueryCreativePointLogsCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the QueryCreativePointLogsCommon operation. The "output" return
// value will be populated with the QueryCreativePointLogsCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned QueryCreativePointLogsCommon Request to send the API call to the service.
// the "output" return value is not valid until after QueryCreativePointLogsCommon Send returns without error.
//
// See QueryCreativePointLogsCommon for more information on using the QueryCreativePointLogsCommon
// API call, and error handling.
//
//    // Example sending a request using the QueryCreativePointLogsCommonRequest method.
//    req, resp := client.QueryCreativePointLogsCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) QueryCreativePointLogsCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opQueryCreativePointLogsCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// QueryCreativePointLogsCommon API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation QueryCreativePointLogsCommon for usage and error information.
func (c *KICKART) QueryCreativePointLogsCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.QueryCreativePointLogsCommonRequest(input)
	return out, req.Send()
}

// QueryCreativePointLogsCommonWithContext is the same as QueryCreativePointLogsCommon with the addition of
// the ability to pass a context and additional request options.
//
// See QueryCreativePointLogsCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) QueryCreativePointLogsCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.QueryCreativePointLogsCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opQueryCreativePointLogs = "QueryCreativePointLogs"

// QueryCreativePointLogsRequest generates a "byteplus/request.Request" representing the
// client's request for the QueryCreativePointLogs operation. The "output" return
// value will be populated with the QueryCreativePointLogsCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned QueryCreativePointLogsCommon Request to send the API call to the service.
// the "output" return value is not valid until after QueryCreativePointLogsCommon Send returns without error.
//
// See QueryCreativePointLogs for more information on using the QueryCreativePointLogs
// API call, and error handling.
//
//    // Example sending a request using the QueryCreativePointLogsRequest method.
//    req, resp := client.QueryCreativePointLogsRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *KICKART) QueryCreativePointLogsRequest(input *QueryCreativePointLogsInput) (req *request.Request, output *QueryCreativePointLogsOutput) {
	op := &request.Operation{
		Name:       opQueryCreativePointLogs,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &QueryCreativePointLogsInput{}
	}

	output = &QueryCreativePointLogsOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// QueryCreativePointLogs API operation for KICKART.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for KICKART's
// API operation QueryCreativePointLogs for usage and error information.
func (c *KICKART) QueryCreativePointLogs(input *QueryCreativePointLogsInput) (*QueryCreativePointLogsOutput, error) {
	req, out := c.QueryCreativePointLogsRequest(input)
	return out, req.Send()
}

// QueryCreativePointLogsWithContext is the same as QueryCreativePointLogs with the addition of
// the ability to pass a context and additional request options.
//
// See QueryCreativePointLogs for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *KICKART) QueryCreativePointLogsWithContext(ctx byteplus.Context, input *QueryCreativePointLogsInput, opts ...request.Option) (*QueryCreativePointLogsOutput, error) {
	req, out := c.QueryCreativePointLogsRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type QueryCreativePointLogsInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	ConsumerItemIds []*int32 `type:"list"`

	FromTs *int32 `type:"int32" json:",omitempty"`

	OperatorIds []*string `type:"list"`

	Page *int32 `type:"int32" json:",omitempty"`

	PageSize *int32 `type:"int32" json:",omitempty"`

	ToTs *int32 `type:"int32" json:",omitempty"`
}

// String returns the string representation
func (s QueryCreativePointLogsInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s QueryCreativePointLogsInput) GoString() string {
	return s.String()
}

// SetConsumerItemIds sets the ConsumerItemIds field's value.
func (s *QueryCreativePointLogsInput) SetConsumerItemIds(v []*int32) *QueryCreativePointLogsInput {
	s.ConsumerItemIds = v
	return s
}

// SetFromTs sets the FromTs field's value.
func (s *QueryCreativePointLogsInput) SetFromTs(v int32) *QueryCreativePointLogsInput {
	s.FromTs = &v
	return s
}

// SetOperatorIds sets the OperatorIds field's value.
func (s *QueryCreativePointLogsInput) SetOperatorIds(v []*string) *QueryCreativePointLogsInput {
	s.OperatorIds = v
	return s
}

// SetPage sets the Page field's value.
func (s *QueryCreativePointLogsInput) SetPage(v int32) *QueryCreativePointLogsInput {
	s.Page = &v
	return s
}

// SetPageSize sets the PageSize field's value.
func (s *QueryCreativePointLogsInput) SetPageSize(v int32) *QueryCreativePointLogsInput {
	s.PageSize = &v
	return s
}

// SetToTs sets the ToTs field's value.
func (s *QueryCreativePointLogsInput) SetToTs(v int32) *QueryCreativePointLogsInput {
	s.ToTs = &v
	return s
}

type QueryCreativePointLogsOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	Logs []*string `type:"list"`

	Total *int32 `type:"int32" json:",omitempty"`
}

// String returns the string representation
func (s QueryCreativePointLogsOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s QueryCreativePointLogsOutput) GoString() string {
	return s.String()
}

// SetLogs sets the Logs field's value.
func (s *QueryCreativePointLogsOutput) SetLogs(v []*string) *QueryCreativePointLogsOutput {
	s.Logs = v
	return s
}

// SetTotal sets the Total field's value.
func (s *QueryCreativePointLogsOutput) SetTotal(v int32) *QueryCreativePointLogsOutput {
	s.Total = &v
	return s
}
