// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package autoscalingiface provides an interface to enable mocking the AUTO_SCALING service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package autoscaling

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
)

// AUTOSCALINGAPI provides an interface to enable mocking the
// autoscaling.AUTOSCALING service client's API operation,
//
//    // byteplus sdk func uses an SDK service client to make a request to
//    // AUTO_SCALING.
//    func myFunc(svc AUTOSCALINGAPI) bool {
//        // Make svc.AttachInstances request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := autoscaling.New(sess)
//
//        myFunc(svc)
//    }
//
type AUTOSCALINGAPI interface {
	AttachInstancesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	AttachInstancesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AttachInstancesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AttachInstances(*AttachInstancesInput) (*AttachInstancesOutput, error)
	AttachInstancesWithContext(byteplus.Context, *AttachInstancesInput, ...request.Option) (*AttachInstancesOutput, error)
	AttachInstancesRequest(*AttachInstancesInput) (*request.Request, *AttachInstancesOutput)

	AttachServerGroupsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	AttachServerGroupsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AttachServerGroupsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AttachServerGroups(*AttachServerGroupsInput) (*AttachServerGroupsOutput, error)
	AttachServerGroupsWithContext(byteplus.Context, *AttachServerGroupsInput, ...request.Option) (*AttachServerGroupsOutput, error)
	AttachServerGroupsRequest(*AttachServerGroupsInput) (*request.Request, *AttachServerGroupsOutput)

	CompleteLifecycleActivityCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CompleteLifecycleActivityCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CompleteLifecycleActivityCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CompleteLifecycleActivity(*CompleteLifecycleActivityInput) (*CompleteLifecycleActivityOutput, error)
	CompleteLifecycleActivityWithContext(byteplus.Context, *CompleteLifecycleActivityInput, ...request.Option) (*CompleteLifecycleActivityOutput, error)
	CompleteLifecycleActivityRequest(*CompleteLifecycleActivityInput) (*request.Request, *CompleteLifecycleActivityOutput)

	CreateLifecycleHookCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateLifecycleHookCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateLifecycleHookCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateLifecycleHook(*CreateLifecycleHookInput) (*CreateLifecycleHookOutput, error)
	CreateLifecycleHookWithContext(byteplus.Context, *CreateLifecycleHookInput, ...request.Option) (*CreateLifecycleHookOutput, error)
	CreateLifecycleHookRequest(*CreateLifecycleHookInput) (*request.Request, *CreateLifecycleHookOutput)

	CreateNotificationConfigurationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateNotificationConfigurationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateNotificationConfigurationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateNotificationConfiguration(*CreateNotificationConfigurationInput) (*CreateNotificationConfigurationOutput, error)
	CreateNotificationConfigurationWithContext(byteplus.Context, *CreateNotificationConfigurationInput, ...request.Option) (*CreateNotificationConfigurationOutput, error)
	CreateNotificationConfigurationRequest(*CreateNotificationConfigurationInput) (*request.Request, *CreateNotificationConfigurationOutput)

	CreateScalingConfigurationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateScalingConfigurationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateScalingConfigurationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateScalingConfiguration(*CreateScalingConfigurationInput) (*CreateScalingConfigurationOutput, error)
	CreateScalingConfigurationWithContext(byteplus.Context, *CreateScalingConfigurationInput, ...request.Option) (*CreateScalingConfigurationOutput, error)
	CreateScalingConfigurationRequest(*CreateScalingConfigurationInput) (*request.Request, *CreateScalingConfigurationOutput)

	CreateScalingGroupCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateScalingGroupCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateScalingGroupCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateScalingGroup(*CreateScalingGroupInput) (*CreateScalingGroupOutput, error)
	CreateScalingGroupWithContext(byteplus.Context, *CreateScalingGroupInput, ...request.Option) (*CreateScalingGroupOutput, error)
	CreateScalingGroupRequest(*CreateScalingGroupInput) (*request.Request, *CreateScalingGroupOutput)

	CreateScalingPolicyCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateScalingPolicyCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateScalingPolicyCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateScalingPolicy(*CreateScalingPolicyInput) (*CreateScalingPolicyOutput, error)
	CreateScalingPolicyWithContext(byteplus.Context, *CreateScalingPolicyInput, ...request.Option) (*CreateScalingPolicyOutput, error)
	CreateScalingPolicyRequest(*CreateScalingPolicyInput) (*request.Request, *CreateScalingPolicyOutput)

	DeleteLifecycleHookCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteLifecycleHookCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteLifecycleHookCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteLifecycleHook(*DeleteLifecycleHookInput) (*DeleteLifecycleHookOutput, error)
	DeleteLifecycleHookWithContext(byteplus.Context, *DeleteLifecycleHookInput, ...request.Option) (*DeleteLifecycleHookOutput, error)
	DeleteLifecycleHookRequest(*DeleteLifecycleHookInput) (*request.Request, *DeleteLifecycleHookOutput)

	DeleteNotificationConfigurationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteNotificationConfigurationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteNotificationConfigurationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteNotificationConfiguration(*DeleteNotificationConfigurationInput) (*DeleteNotificationConfigurationOutput, error)
	DeleteNotificationConfigurationWithContext(byteplus.Context, *DeleteNotificationConfigurationInput, ...request.Option) (*DeleteNotificationConfigurationOutput, error)
	DeleteNotificationConfigurationRequest(*DeleteNotificationConfigurationInput) (*request.Request, *DeleteNotificationConfigurationOutput)

	DeleteScalingConfigurationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteScalingConfigurationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteScalingConfigurationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteScalingConfiguration(*DeleteScalingConfigurationInput) (*DeleteScalingConfigurationOutput, error)
	DeleteScalingConfigurationWithContext(byteplus.Context, *DeleteScalingConfigurationInput, ...request.Option) (*DeleteScalingConfigurationOutput, error)
	DeleteScalingConfigurationRequest(*DeleteScalingConfigurationInput) (*request.Request, *DeleteScalingConfigurationOutput)

	DeleteScalingGroupCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteScalingGroupCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteScalingGroupCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteScalingGroup(*DeleteScalingGroupInput) (*DeleteScalingGroupOutput, error)
	DeleteScalingGroupWithContext(byteplus.Context, *DeleteScalingGroupInput, ...request.Option) (*DeleteScalingGroupOutput, error)
	DeleteScalingGroupRequest(*DeleteScalingGroupInput) (*request.Request, *DeleteScalingGroupOutput)

	DeleteScalingPolicyCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteScalingPolicyCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteScalingPolicyCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteScalingPolicy(*DeleteScalingPolicyInput) (*DeleteScalingPolicyOutput, error)
	DeleteScalingPolicyWithContext(byteplus.Context, *DeleteScalingPolicyInput, ...request.Option) (*DeleteScalingPolicyOutput, error)
	DeleteScalingPolicyRequest(*DeleteScalingPolicyInput) (*request.Request, *DeleteScalingPolicyOutput)

	DescribeLifecycleActivitiesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeLifecycleActivitiesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeLifecycleActivitiesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeLifecycleActivities(*DescribeLifecycleActivitiesInput) (*DescribeLifecycleActivitiesOutput, error)
	DescribeLifecycleActivitiesWithContext(byteplus.Context, *DescribeLifecycleActivitiesInput, ...request.Option) (*DescribeLifecycleActivitiesOutput, error)
	DescribeLifecycleActivitiesRequest(*DescribeLifecycleActivitiesInput) (*request.Request, *DescribeLifecycleActivitiesOutput)

	DescribeLifecycleHooksCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeLifecycleHooksCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeLifecycleHooksCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeLifecycleHooks(*DescribeLifecycleHooksInput) (*DescribeLifecycleHooksOutput, error)
	DescribeLifecycleHooksWithContext(byteplus.Context, *DescribeLifecycleHooksInput, ...request.Option) (*DescribeLifecycleHooksOutput, error)
	DescribeLifecycleHooksRequest(*DescribeLifecycleHooksInput) (*request.Request, *DescribeLifecycleHooksOutput)

	DescribeNotificationConfigurationsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeNotificationConfigurationsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeNotificationConfigurationsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeNotificationConfigurations(*DescribeNotificationConfigurationsInput) (*DescribeNotificationConfigurationsOutput, error)
	DescribeNotificationConfigurationsWithContext(byteplus.Context, *DescribeNotificationConfigurationsInput, ...request.Option) (*DescribeNotificationConfigurationsOutput, error)
	DescribeNotificationConfigurationsRequest(*DescribeNotificationConfigurationsInput) (*request.Request, *DescribeNotificationConfigurationsOutput)

	DescribeScalingActivitiesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeScalingActivitiesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeScalingActivitiesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeScalingActivities(*DescribeScalingActivitiesInput) (*DescribeScalingActivitiesOutput, error)
	DescribeScalingActivitiesWithContext(byteplus.Context, *DescribeScalingActivitiesInput, ...request.Option) (*DescribeScalingActivitiesOutput, error)
	DescribeScalingActivitiesRequest(*DescribeScalingActivitiesInput) (*request.Request, *DescribeScalingActivitiesOutput)

	DescribeScalingConfigurationsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeScalingConfigurationsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeScalingConfigurationsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeScalingConfigurations(*DescribeScalingConfigurationsInput) (*DescribeScalingConfigurationsOutput, error)
	DescribeScalingConfigurationsWithContext(byteplus.Context, *DescribeScalingConfigurationsInput, ...request.Option) (*DescribeScalingConfigurationsOutput, error)
	DescribeScalingConfigurationsRequest(*DescribeScalingConfigurationsInput) (*request.Request, *DescribeScalingConfigurationsOutput)

	DescribeScalingGroupsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeScalingGroupsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeScalingGroupsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeScalingGroups(*DescribeScalingGroupsInput) (*DescribeScalingGroupsOutput, error)
	DescribeScalingGroupsWithContext(byteplus.Context, *DescribeScalingGroupsInput, ...request.Option) (*DescribeScalingGroupsOutput, error)
	DescribeScalingGroupsRequest(*DescribeScalingGroupsInput) (*request.Request, *DescribeScalingGroupsOutput)

	DescribeScalingInstancesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeScalingInstancesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeScalingInstancesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeScalingInstances(*DescribeScalingInstancesInput) (*DescribeScalingInstancesOutput, error)
	DescribeScalingInstancesWithContext(byteplus.Context, *DescribeScalingInstancesInput, ...request.Option) (*DescribeScalingInstancesOutput, error)
	DescribeScalingInstancesRequest(*DescribeScalingInstancesInput) (*request.Request, *DescribeScalingInstancesOutput)

	DescribeScalingPoliciesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeScalingPoliciesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeScalingPoliciesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeScalingPolicies(*DescribeScalingPoliciesInput) (*DescribeScalingPoliciesOutput, error)
	DescribeScalingPoliciesWithContext(byteplus.Context, *DescribeScalingPoliciesInput, ...request.Option) (*DescribeScalingPoliciesOutput, error)
	DescribeScalingPoliciesRequest(*DescribeScalingPoliciesInput) (*request.Request, *DescribeScalingPoliciesOutput)

	DetachInstancesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DetachInstancesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DetachInstancesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DetachInstances(*DetachInstancesInput) (*DetachInstancesOutput, error)
	DetachInstancesWithContext(byteplus.Context, *DetachInstancesInput, ...request.Option) (*DetachInstancesOutput, error)
	DetachInstancesRequest(*DetachInstancesInput) (*request.Request, *DetachInstancesOutput)

	DetachServerGroupsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DetachServerGroupsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DetachServerGroupsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DetachServerGroups(*DetachServerGroupsInput) (*DetachServerGroupsOutput, error)
	DetachServerGroupsWithContext(byteplus.Context, *DetachServerGroupsInput, ...request.Option) (*DetachServerGroupsOutput, error)
	DetachServerGroupsRequest(*DetachServerGroupsInput) (*request.Request, *DetachServerGroupsOutput)

	DisableScalingGroupCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DisableScalingGroupCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DisableScalingGroupCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DisableScalingGroup(*DisableScalingGroupInput) (*DisableScalingGroupOutput, error)
	DisableScalingGroupWithContext(byteplus.Context, *DisableScalingGroupInput, ...request.Option) (*DisableScalingGroupOutput, error)
	DisableScalingGroupRequest(*DisableScalingGroupInput) (*request.Request, *DisableScalingGroupOutput)

	DisableScalingPolicyCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DisableScalingPolicyCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DisableScalingPolicyCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DisableScalingPolicy(*DisableScalingPolicyInput) (*DisableScalingPolicyOutput, error)
	DisableScalingPolicyWithContext(byteplus.Context, *DisableScalingPolicyInput, ...request.Option) (*DisableScalingPolicyOutput, error)
	DisableScalingPolicyRequest(*DisableScalingPolicyInput) (*request.Request, *DisableScalingPolicyOutput)

	EnableScalingConfigurationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	EnableScalingConfigurationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	EnableScalingConfigurationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	EnableScalingConfiguration(*EnableScalingConfigurationInput) (*EnableScalingConfigurationOutput, error)
	EnableScalingConfigurationWithContext(byteplus.Context, *EnableScalingConfigurationInput, ...request.Option) (*EnableScalingConfigurationOutput, error)
	EnableScalingConfigurationRequest(*EnableScalingConfigurationInput) (*request.Request, *EnableScalingConfigurationOutput)

	EnableScalingGroupCommon(*map[string]interface{}) (*map[string]interface{}, error)
	EnableScalingGroupCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	EnableScalingGroupCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	EnableScalingGroup(*EnableScalingGroupInput) (*EnableScalingGroupOutput, error)
	EnableScalingGroupWithContext(byteplus.Context, *EnableScalingGroupInput, ...request.Option) (*EnableScalingGroupOutput, error)
	EnableScalingGroupRequest(*EnableScalingGroupInput) (*request.Request, *EnableScalingGroupOutput)

	EnableScalingPolicyCommon(*map[string]interface{}) (*map[string]interface{}, error)
	EnableScalingPolicyCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	EnableScalingPolicyCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	EnableScalingPolicy(*EnableScalingPolicyInput) (*EnableScalingPolicyOutput, error)
	EnableScalingPolicyWithContext(byteplus.Context, *EnableScalingPolicyInput, ...request.Option) (*EnableScalingPolicyOutput, error)
	EnableScalingPolicyRequest(*EnableScalingPolicyInput) (*request.Request, *EnableScalingPolicyOutput)

	EnterStandbyCommon(*map[string]interface{}) (*map[string]interface{}, error)
	EnterStandbyCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	EnterStandbyCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	EnterStandby(*EnterStandbyInput) (*EnterStandbyOutput, error)
	EnterStandbyWithContext(byteplus.Context, *EnterStandbyInput, ...request.Option) (*EnterStandbyOutput, error)
	EnterStandbyRequest(*EnterStandbyInput) (*request.Request, *EnterStandbyOutput)

	ExitStandbyCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ExitStandbyCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ExitStandbyCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ExitStandby(*ExitStandbyInput) (*ExitStandbyOutput, error)
	ExitStandbyWithContext(byteplus.Context, *ExitStandbyInput, ...request.Option) (*ExitStandbyOutput, error)
	ExitStandbyRequest(*ExitStandbyInput) (*request.Request, *ExitStandbyOutput)

	ListTagResourcesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListTagResourcesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListTagResourcesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListTagResources(*ListTagResourcesInput) (*ListTagResourcesOutput, error)
	ListTagResourcesWithContext(byteplus.Context, *ListTagResourcesInput, ...request.Option) (*ListTagResourcesOutput, error)
	ListTagResourcesRequest(*ListTagResourcesInput) (*request.Request, *ListTagResourcesOutput)

	ModifyLifecycleHookCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyLifecycleHookCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyLifecycleHookCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyLifecycleHook(*ModifyLifecycleHookInput) (*ModifyLifecycleHookOutput, error)
	ModifyLifecycleHookWithContext(byteplus.Context, *ModifyLifecycleHookInput, ...request.Option) (*ModifyLifecycleHookOutput, error)
	ModifyLifecycleHookRequest(*ModifyLifecycleHookInput) (*request.Request, *ModifyLifecycleHookOutput)

	ModifyNotificationConfigurationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyNotificationConfigurationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyNotificationConfigurationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyNotificationConfiguration(*ModifyNotificationConfigurationInput) (*ModifyNotificationConfigurationOutput, error)
	ModifyNotificationConfigurationWithContext(byteplus.Context, *ModifyNotificationConfigurationInput, ...request.Option) (*ModifyNotificationConfigurationOutput, error)
	ModifyNotificationConfigurationRequest(*ModifyNotificationConfigurationInput) (*request.Request, *ModifyNotificationConfigurationOutput)

	ModifyScalingConfigurationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyScalingConfigurationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyScalingConfigurationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyScalingConfiguration(*ModifyScalingConfigurationInput) (*ModifyScalingConfigurationOutput, error)
	ModifyScalingConfigurationWithContext(byteplus.Context, *ModifyScalingConfigurationInput, ...request.Option) (*ModifyScalingConfigurationOutput, error)
	ModifyScalingConfigurationRequest(*ModifyScalingConfigurationInput) (*request.Request, *ModifyScalingConfigurationOutput)

	ModifyScalingGroupCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyScalingGroupCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyScalingGroupCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyScalingGroup(*ModifyScalingGroupInput) (*ModifyScalingGroupOutput, error)
	ModifyScalingGroupWithContext(byteplus.Context, *ModifyScalingGroupInput, ...request.Option) (*ModifyScalingGroupOutput, error)
	ModifyScalingGroupRequest(*ModifyScalingGroupInput) (*request.Request, *ModifyScalingGroupOutput)

	ModifyScalingPolicyCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyScalingPolicyCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyScalingPolicyCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyScalingPolicy(*ModifyScalingPolicyInput) (*ModifyScalingPolicyOutput, error)
	ModifyScalingPolicyWithContext(byteplus.Context, *ModifyScalingPolicyInput, ...request.Option) (*ModifyScalingPolicyOutput, error)
	ModifyScalingPolicyRequest(*ModifyScalingPolicyInput) (*request.Request, *ModifyScalingPolicyOutput)

	RemoveInstancesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	RemoveInstancesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	RemoveInstancesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	RemoveInstances(*RemoveInstancesInput) (*RemoveInstancesOutput, error)
	RemoveInstancesWithContext(byteplus.Context, *RemoveInstancesInput, ...request.Option) (*RemoveInstancesOutput, error)
	RemoveInstancesRequest(*RemoveInstancesInput) (*request.Request, *RemoveInstancesOutput)

	ResumeProcessesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ResumeProcessesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ResumeProcessesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ResumeProcesses(*ResumeProcessesInput) (*ResumeProcessesOutput, error)
	ResumeProcessesWithContext(byteplus.Context, *ResumeProcessesInput, ...request.Option) (*ResumeProcessesOutput, error)
	ResumeProcessesRequest(*ResumeProcessesInput) (*request.Request, *ResumeProcessesOutput)

	SetInstancesProtectionCommon(*map[string]interface{}) (*map[string]interface{}, error)
	SetInstancesProtectionCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	SetInstancesProtectionCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	SetInstancesProtection(*SetInstancesProtectionInput) (*SetInstancesProtectionOutput, error)
	SetInstancesProtectionWithContext(byteplus.Context, *SetInstancesProtectionInput, ...request.Option) (*SetInstancesProtectionOutput, error)
	SetInstancesProtectionRequest(*SetInstancesProtectionInput) (*request.Request, *SetInstancesProtectionOutput)

	SuspendProcessesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	SuspendProcessesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	SuspendProcessesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	SuspendProcesses(*SuspendProcessesInput) (*SuspendProcessesOutput, error)
	SuspendProcessesWithContext(byteplus.Context, *SuspendProcessesInput, ...request.Option) (*SuspendProcessesOutput, error)
	SuspendProcessesRequest(*SuspendProcessesInput) (*request.Request, *SuspendProcessesOutput)

	TagResourcesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	TagResourcesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	TagResourcesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	TagResources(*TagResourcesInput) (*TagResourcesOutput, error)
	TagResourcesWithContext(byteplus.Context, *TagResourcesInput, ...request.Option) (*TagResourcesOutput, error)
	TagResourcesRequest(*TagResourcesInput) (*request.Request, *TagResourcesOutput)

	UntagResourcesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	UntagResourcesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UntagResourcesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UntagResources(*UntagResourcesInput) (*UntagResourcesOutput, error)
	UntagResourcesWithContext(byteplus.Context, *UntagResourcesInput, ...request.Option) (*UntagResourcesOutput, error)
	UntagResourcesRequest(*UntagResourcesInput) (*request.Request, *UntagResourcesOutput)
}

var _ AUTOSCALINGAPI = (*AUTOSCALING)(nil)
