// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package cpaas

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opCreateTemplateV2Common = "CreateTemplateV2"

// CreateTemplateV2CommonRequest generates a "byteplus/request.Request" representing the
// client's request for the CreateTemplateV2Common operation. The "output" return
// value will be populated with the CreateTemplateV2Common request's response once the request completes
// successfully.
//
// Use "Send" method on the returned CreateTemplateV2Common Request to send the API call to the service.
// the "output" return value is not valid until after CreateTemplateV2Common Send returns without error.
//
// See CreateTemplateV2Common for more information on using the CreateTemplateV2Common
// API call, and error handling.
//
//    // Example sending a request using the CreateTemplateV2CommonRequest method.
//    req, resp := client.CreateTemplateV2CommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *CPAAS) CreateTemplateV2CommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opCreateTemplateV2Common,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// CreateTemplateV2Common API operation for CPAAS.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for CPAAS's
// API operation CreateTemplateV2Common for usage and error information.
func (c *CPAAS) CreateTemplateV2Common(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.CreateTemplateV2CommonRequest(input)
	return out, req.Send()
}

// CreateTemplateV2CommonWithContext is the same as CreateTemplateV2Common with the addition of
// the ability to pass a context and additional request options.
//
// See CreateTemplateV2Common for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *CPAAS) CreateTemplateV2CommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.CreateTemplateV2CommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opCreateTemplateV2 = "CreateTemplateV2"

// CreateTemplateV2Request generates a "byteplus/request.Request" representing the
// client's request for the CreateTemplateV2 operation. The "output" return
// value will be populated with the CreateTemplateV2Common request's response once the request completes
// successfully.
//
// Use "Send" method on the returned CreateTemplateV2Common Request to send the API call to the service.
// the "output" return value is not valid until after CreateTemplateV2Common Send returns without error.
//
// See CreateTemplateV2 for more information on using the CreateTemplateV2
// API call, and error handling.
//
//    // Example sending a request using the CreateTemplateV2Request method.
//    req, resp := client.CreateTemplateV2Request(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *CPAAS) CreateTemplateV2Request(input *CreateTemplateV2Input) (req *request.Request, output *CreateTemplateV2Output) {
	op := &request.Operation{
		Name:       opCreateTemplateV2,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &CreateTemplateV2Input{}
	}

	output = &CreateTemplateV2Output{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// CreateTemplateV2 API operation for CPAAS.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for CPAAS's
// API operation CreateTemplateV2 for usage and error information.
func (c *CPAAS) CreateTemplateV2(input *CreateTemplateV2Input) (*CreateTemplateV2Output, error) {
	req, out := c.CreateTemplateV2Request(input)
	return out, req.Send()
}

// CreateTemplateV2WithContext is the same as CreateTemplateV2 with the addition of
// the ability to pass a context and additional request options.
//
// See CreateTemplateV2 for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *CPAAS) CreateTemplateV2WithContext(ctx byteplus.Context, input *CreateTemplateV2Input, opts ...request.Option) (*CreateTemplateV2Output, error) {
	req, out := c.CreateTemplateV2Request(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type ActionForCreateTemplateV2Input struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Action *string `type:"string" json:",omitempty"`

	EventName *string `type:"string" json:",omitempty"`

	EventType *string `type:"string" json:",omitempty"`

	ExtendAttrs *ExtendAttrsForCreateTemplateV2Input `type:"structure" json:",omitempty"`
}

// String returns the string representation
func (s ActionForCreateTemplateV2Input) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ActionForCreateTemplateV2Input) GoString() string {
	return s.String()
}

// SetAction sets the Action field's value.
func (s *ActionForCreateTemplateV2Input) SetAction(v string) *ActionForCreateTemplateV2Input {
	s.Action = &v
	return s
}

// SetEventName sets the EventName field's value.
func (s *ActionForCreateTemplateV2Input) SetEventName(v string) *ActionForCreateTemplateV2Input {
	s.EventName = &v
	return s
}

// SetEventType sets the EventType field's value.
func (s *ActionForCreateTemplateV2Input) SetEventType(v string) *ActionForCreateTemplateV2Input {
	s.EventType = &v
	return s
}

// SetExtendAttrs sets the ExtendAttrs field's value.
func (s *ActionForCreateTemplateV2Input) SetExtendAttrs(v *ExtendAttrsForCreateTemplateV2Input) *ActionForCreateTemplateV2Input {
	s.ExtendAttrs = v
	return s
}

type CreateTemplateV2Input struct {
	_ struct{} `type:"structure" json:",omitempty"`

	BusinessType *string `type:"string" json:",omitempty"`

	EnableShortUrl *string `type:"string" json:",omitempty"`

	Language *string `type:"string" json:",omitempty"`

	// SceneTemplateName is a required field
	SceneTemplateName *string `type:"string" json:",omitempty" required:"true"`

	Signature *string `type:"string" json:",omitempty"`

	SubAccountId *string `type:"string" json:",omitempty"`

	TemplateList []*TemplateListForCreateTemplateV2Input `type:"list"`

	WabaId *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s CreateTemplateV2Input) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateTemplateV2Input) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *CreateTemplateV2Input) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "CreateTemplateV2Input"}
	if s.SceneTemplateName == nil {
		invalidParams.Add(request.NewErrParamRequired("SceneTemplateName"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetBusinessType sets the BusinessType field's value.
func (s *CreateTemplateV2Input) SetBusinessType(v string) *CreateTemplateV2Input {
	s.BusinessType = &v
	return s
}

// SetEnableShortUrl sets the EnableShortUrl field's value.
func (s *CreateTemplateV2Input) SetEnableShortUrl(v string) *CreateTemplateV2Input {
	s.EnableShortUrl = &v
	return s
}

// SetLanguage sets the Language field's value.
func (s *CreateTemplateV2Input) SetLanguage(v string) *CreateTemplateV2Input {
	s.Language = &v
	return s
}

// SetSceneTemplateName sets the SceneTemplateName field's value.
func (s *CreateTemplateV2Input) SetSceneTemplateName(v string) *CreateTemplateV2Input {
	s.SceneTemplateName = &v
	return s
}

// SetSignature sets the Signature field's value.
func (s *CreateTemplateV2Input) SetSignature(v string) *CreateTemplateV2Input {
	s.Signature = &v
	return s
}

// SetSubAccountId sets the SubAccountId field's value.
func (s *CreateTemplateV2Input) SetSubAccountId(v string) *CreateTemplateV2Input {
	s.SubAccountId = &v
	return s
}

// SetTemplateList sets the TemplateList field's value.
func (s *CreateTemplateV2Input) SetTemplateList(v []*TemplateListForCreateTemplateV2Input) *CreateTemplateV2Input {
	s.TemplateList = v
	return s
}

// SetWabaId sets the WabaId field's value.
func (s *CreateTemplateV2Input) SetWabaId(v string) *CreateTemplateV2Input {
	s.WabaId = &v
	return s
}

type CreateTemplateV2Output struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	Data *DataForCreateTemplateV2Output `type:"structure" json:",omitempty"`

	Message *string `type:"string" json:",omitempty"`

	Success *bool `type:"boolean" json:",omitempty"`
}

// String returns the string representation
func (s CreateTemplateV2Output) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateTemplateV2Output) GoString() string {
	return s.String()
}

// SetData sets the Data field's value.
func (s *CreateTemplateV2Output) SetData(v *DataForCreateTemplateV2Output) *CreateTemplateV2Output {
	s.Data = v
	return s
}

// SetMessage sets the Message field's value.
func (s *CreateTemplateV2Output) SetMessage(v string) *CreateTemplateV2Output {
	s.Message = &v
	return s
}

// SetSuccess sets the Success field's value.
func (s *CreateTemplateV2Output) SetSuccess(v bool) *CreateTemplateV2Output {
	s.Success = &v
	return s
}

type DataForCreateTemplateV2Output struct {
	_ struct{} `type:"structure" json:",omitempty"`

	SceneTemplateCode *string `type:"string" json:",omitempty"`

	SceneTemplateName *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s DataForCreateTemplateV2Output) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s DataForCreateTemplateV2Output) GoString() string {
	return s.String()
}

// SetSceneTemplateCode sets the SceneTemplateCode field's value.
func (s *DataForCreateTemplateV2Output) SetSceneTemplateCode(v string) *DataForCreateTemplateV2Output {
	s.SceneTemplateCode = &v
	return s
}

// SetSceneTemplateName sets the SceneTemplateName field's value.
func (s *DataForCreateTemplateV2Output) SetSceneTemplateName(v string) *DataForCreateTemplateV2Output {
	s.SceneTemplateName = &v
	return s
}

type ElementStyleForCreateTemplateV2Input struct {
	_ struct{} `type:"structure" json:",omitempty"`

	ElementType *string `type:"string" json:",omitempty"`

	ExpiresTime *int32 `type:"int32" json:",omitempty"`

	HasExpires *bool `type:"boolean" json:",omitempty"`

	HasSecurity *bool `type:"boolean" json:",omitempty"`

	RealContent *string `type:"string" json:",omitempty"`

	ResourceCode *string `type:"string" json:",omitempty"`

	ResourceName *string `type:"string" json:",omitempty"`

	ResourceUrl *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ElementStyleForCreateTemplateV2Input) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ElementStyleForCreateTemplateV2Input) GoString() string {
	return s.String()
}

// SetElementType sets the ElementType field's value.
func (s *ElementStyleForCreateTemplateV2Input) SetElementType(v string) *ElementStyleForCreateTemplateV2Input {
	s.ElementType = &v
	return s
}

// SetExpiresTime sets the ExpiresTime field's value.
func (s *ElementStyleForCreateTemplateV2Input) SetExpiresTime(v int32) *ElementStyleForCreateTemplateV2Input {
	s.ExpiresTime = &v
	return s
}

// SetHasExpires sets the HasExpires field's value.
func (s *ElementStyleForCreateTemplateV2Input) SetHasExpires(v bool) *ElementStyleForCreateTemplateV2Input {
	s.HasExpires = &v
	return s
}

// SetHasSecurity sets the HasSecurity field's value.
func (s *ElementStyleForCreateTemplateV2Input) SetHasSecurity(v bool) *ElementStyleForCreateTemplateV2Input {
	s.HasSecurity = &v
	return s
}

// SetRealContent sets the RealContent field's value.
func (s *ElementStyleForCreateTemplateV2Input) SetRealContent(v string) *ElementStyleForCreateTemplateV2Input {
	s.RealContent = &v
	return s
}

// SetResourceCode sets the ResourceCode field's value.
func (s *ElementStyleForCreateTemplateV2Input) SetResourceCode(v string) *ElementStyleForCreateTemplateV2Input {
	s.ResourceCode = &v
	return s
}

// SetResourceName sets the ResourceName field's value.
func (s *ElementStyleForCreateTemplateV2Input) SetResourceName(v string) *ElementStyleForCreateTemplateV2Input {
	s.ResourceName = &v
	return s
}

// SetResourceUrl sets the ResourceUrl field's value.
func (s *ElementStyleForCreateTemplateV2Input) SetResourceUrl(v string) *ElementStyleForCreateTemplateV2Input {
	s.ResourceUrl = &v
	return s
}

type ExtendAttrsForCreateTemplateV2Input struct {
	_ struct{} `type:"structure" json:",omitempty"`

	CouponCode *string `type:"string" json:",omitempty"`

	PhoneNumber *string `type:"string" json:",omitempty"`

	Variable *string `type:"string" json:",omitempty"`

	WebsiteUrl *string `type:"string" json:",omitempty"`

	WebsiteUrlType *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s ExtendAttrsForCreateTemplateV2Input) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ExtendAttrsForCreateTemplateV2Input) GoString() string {
	return s.String()
}

// SetCouponCode sets the CouponCode field's value.
func (s *ExtendAttrsForCreateTemplateV2Input) SetCouponCode(v string) *ExtendAttrsForCreateTemplateV2Input {
	s.CouponCode = &v
	return s
}

// SetPhoneNumber sets the PhoneNumber field's value.
func (s *ExtendAttrsForCreateTemplateV2Input) SetPhoneNumber(v string) *ExtendAttrsForCreateTemplateV2Input {
	s.PhoneNumber = &v
	return s
}

// SetVariable sets the Variable field's value.
func (s *ExtendAttrsForCreateTemplateV2Input) SetVariable(v string) *ExtendAttrsForCreateTemplateV2Input {
	s.Variable = &v
	return s
}

// SetWebsiteUrl sets the WebsiteUrl field's value.
func (s *ExtendAttrsForCreateTemplateV2Input) SetWebsiteUrl(v string) *ExtendAttrsForCreateTemplateV2Input {
	s.WebsiteUrl = &v
	return s
}

// SetWebsiteUrlType sets the WebsiteUrlType field's value.
func (s *ExtendAttrsForCreateTemplateV2Input) SetWebsiteUrlType(v string) *ExtendAttrsForCreateTemplateV2Input {
	s.WebsiteUrlType = &v
	return s
}

type PageDTOListForCreateTemplateV2Input struct {
	_ struct{} `type:"structure" json:",omitempty"`

	PageElementDTOList []*PageElementDTOListForCreateTemplateV2Input `type:"list"`

	PageLinkList []*PageLinkListForCreateTemplateV2Input `type:"list"`

	PageName *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s PageDTOListForCreateTemplateV2Input) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s PageDTOListForCreateTemplateV2Input) GoString() string {
	return s.String()
}

// SetPageElementDTOList sets the PageElementDTOList field's value.
func (s *PageDTOListForCreateTemplateV2Input) SetPageElementDTOList(v []*PageElementDTOListForCreateTemplateV2Input) *PageDTOListForCreateTemplateV2Input {
	s.PageElementDTOList = v
	return s
}

// SetPageLinkList sets the PageLinkList field's value.
func (s *PageDTOListForCreateTemplateV2Input) SetPageLinkList(v []*PageLinkListForCreateTemplateV2Input) *PageDTOListForCreateTemplateV2Input {
	s.PageLinkList = v
	return s
}

// SetPageName sets the PageName field's value.
func (s *PageDTOListForCreateTemplateV2Input) SetPageName(v string) *PageDTOListForCreateTemplateV2Input {
	s.PageName = &v
	return s
}

type PageElementDTOListForCreateTemplateV2Input struct {
	_ struct{} `type:"structure" json:",omitempty"`

	ElementStyle *ElementStyleForCreateTemplateV2Input `type:"structure" json:",omitempty"`

	ElementType *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s PageElementDTOListForCreateTemplateV2Input) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s PageElementDTOListForCreateTemplateV2Input) GoString() string {
	return s.String()
}

// SetElementStyle sets the ElementStyle field's value.
func (s *PageElementDTOListForCreateTemplateV2Input) SetElementStyle(v *ElementStyleForCreateTemplateV2Input) *PageElementDTOListForCreateTemplateV2Input {
	s.ElementStyle = v
	return s
}

// SetElementType sets the ElementType field's value.
func (s *PageElementDTOListForCreateTemplateV2Input) SetElementType(v string) *PageElementDTOListForCreateTemplateV2Input {
	s.ElementType = &v
	return s
}

type PageLinkListForCreateTemplateV2Input struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Action *ActionForCreateTemplateV2Input `type:"structure" json:",omitempty"`

	ElementType *string `type:"string" json:",omitempty"`

	LinkName *string `type:"string" json:",omitempty"`

	LinkType *string `type:"string" json:",omitempty"`

	OrderId *int32 `type:"int32" json:",omitempty"`
}

// String returns the string representation
func (s PageLinkListForCreateTemplateV2Input) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s PageLinkListForCreateTemplateV2Input) GoString() string {
	return s.String()
}

// SetAction sets the Action field's value.
func (s *PageLinkListForCreateTemplateV2Input) SetAction(v *ActionForCreateTemplateV2Input) *PageLinkListForCreateTemplateV2Input {
	s.Action = v
	return s
}

// SetElementType sets the ElementType field's value.
func (s *PageLinkListForCreateTemplateV2Input) SetElementType(v string) *PageLinkListForCreateTemplateV2Input {
	s.ElementType = &v
	return s
}

// SetLinkName sets the LinkName field's value.
func (s *PageLinkListForCreateTemplateV2Input) SetLinkName(v string) *PageLinkListForCreateTemplateV2Input {
	s.LinkName = &v
	return s
}

// SetLinkType sets the LinkType field's value.
func (s *PageLinkListForCreateTemplateV2Input) SetLinkType(v string) *PageLinkListForCreateTemplateV2Input {
	s.LinkType = &v
	return s
}

// SetOrderId sets the OrderId field's value.
func (s *PageLinkListForCreateTemplateV2Input) SetOrderId(v int32) *PageLinkListForCreateTemplateV2Input {
	s.OrderId = &v
	return s
}

type TemplateListForCreateTemplateV2Input struct {
	_ struct{} `type:"structure" json:",omitempty"`

	CardButtonType []*string `type:"list"`

	CardHeaderType *string `type:"string" json:",omitempty"`

	CarouselBody *string `type:"string" json:",omitempty"`

	Format *string `type:"string" json:",omitempty"`

	PageDTOList []*PageDTOListForCreateTemplateV2Input `type:"list"`

	TemplateType *string `type:"string" json:",omitempty"`

	VariablesDTOList []*VariablesDTOListForCreateTemplateV2Input `type:"list"`

	WhatsappCatagory *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s TemplateListForCreateTemplateV2Input) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s TemplateListForCreateTemplateV2Input) GoString() string {
	return s.String()
}

// SetCardButtonType sets the CardButtonType field's value.
func (s *TemplateListForCreateTemplateV2Input) SetCardButtonType(v []*string) *TemplateListForCreateTemplateV2Input {
	s.CardButtonType = v
	return s
}

// SetCardHeaderType sets the CardHeaderType field's value.
func (s *TemplateListForCreateTemplateV2Input) SetCardHeaderType(v string) *TemplateListForCreateTemplateV2Input {
	s.CardHeaderType = &v
	return s
}

// SetCarouselBody sets the CarouselBody field's value.
func (s *TemplateListForCreateTemplateV2Input) SetCarouselBody(v string) *TemplateListForCreateTemplateV2Input {
	s.CarouselBody = &v
	return s
}

// SetFormat sets the Format field's value.
func (s *TemplateListForCreateTemplateV2Input) SetFormat(v string) *TemplateListForCreateTemplateV2Input {
	s.Format = &v
	return s
}

// SetPageDTOList sets the PageDTOList field's value.
func (s *TemplateListForCreateTemplateV2Input) SetPageDTOList(v []*PageDTOListForCreateTemplateV2Input) *TemplateListForCreateTemplateV2Input {
	s.PageDTOList = v
	return s
}

// SetTemplateType sets the TemplateType field's value.
func (s *TemplateListForCreateTemplateV2Input) SetTemplateType(v string) *TemplateListForCreateTemplateV2Input {
	s.TemplateType = &v
	return s
}

// SetVariablesDTOList sets the VariablesDTOList field's value.
func (s *TemplateListForCreateTemplateV2Input) SetVariablesDTOList(v []*VariablesDTOListForCreateTemplateV2Input) *TemplateListForCreateTemplateV2Input {
	s.VariablesDTOList = v
	return s
}

// SetWhatsappCatagory sets the WhatsappCatagory field's value.
func (s *TemplateListForCreateTemplateV2Input) SetWhatsappCatagory(v string) *TemplateListForCreateTemplateV2Input {
	s.WhatsappCatagory = &v
	return s
}

type VariablesDTOListForCreateTemplateV2Input struct {
	_ struct{} `type:"structure" json:",omitempty"`

	DefaultValue *string `type:"string" json:",omitempty"`

	Format *string `type:"string" json:",omitempty"`

	UniqueVariableCode *string `type:"string" json:",omitempty"`

	VariableCode *string `type:"string" json:",omitempty"`

	VariableName *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s VariablesDTOListForCreateTemplateV2Input) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s VariablesDTOListForCreateTemplateV2Input) GoString() string {
	return s.String()
}

// SetDefaultValue sets the DefaultValue field's value.
func (s *VariablesDTOListForCreateTemplateV2Input) SetDefaultValue(v string) *VariablesDTOListForCreateTemplateV2Input {
	s.DefaultValue = &v
	return s
}

// SetFormat sets the Format field's value.
func (s *VariablesDTOListForCreateTemplateV2Input) SetFormat(v string) *VariablesDTOListForCreateTemplateV2Input {
	s.Format = &v
	return s
}

// SetUniqueVariableCode sets the UniqueVariableCode field's value.
func (s *VariablesDTOListForCreateTemplateV2Input) SetUniqueVariableCode(v string) *VariablesDTOListForCreateTemplateV2Input {
	s.UniqueVariableCode = &v
	return s
}

// SetVariableCode sets the VariableCode field's value.
func (s *VariablesDTOListForCreateTemplateV2Input) SetVariableCode(v string) *VariablesDTOListForCreateTemplateV2Input {
	s.VariableCode = &v
	return s
}

// SetVariableName sets the VariableName field's value.
func (s *VariablesDTOListForCreateTemplateV2Input) SetVariableName(v string) *VariablesDTOListForCreateTemplateV2Input {
	s.VariableName = &v
	return s
}
