// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package vs

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opCreateVoiceTaskCommon = "CreateVoiceTask"

// CreateVoiceTaskCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the CreateVoiceTaskCommon operation. The "output" return
// value will be populated with the CreateVoiceTaskCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned CreateVoiceTaskCommon Request to send the API call to the service.
// the "output" return value is not valid until after CreateVoiceTaskCommon Send returns without error.
//
// See CreateVoiceTaskCommon for more information on using the CreateVoiceTaskCommon
// API call, and error handling.
//
//    // Example sending a request using the CreateVoiceTaskCommonRequest method.
//    req, resp := client.CreateVoiceTaskCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *VS) CreateVoiceTaskCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opCreateVoiceTaskCommon,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// CreateVoiceTaskCommon API operation for VS.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for VS's
// API operation CreateVoiceTaskCommon for usage and error information.
func (c *VS) CreateVoiceTaskCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.CreateVoiceTaskCommonRequest(input)
	return out, req.Send()
}

// CreateVoiceTaskCommonWithContext is the same as CreateVoiceTaskCommon with the addition of
// the ability to pass a context and additional request options.
//
// See CreateVoiceTaskCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *VS) CreateVoiceTaskCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.CreateVoiceTaskCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opCreateVoiceTask = "CreateVoiceTask"

// CreateVoiceTaskRequest generates a "byteplus/request.Request" representing the
// client's request for the CreateVoiceTask operation. The "output" return
// value will be populated with the CreateVoiceTaskCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned CreateVoiceTaskCommon Request to send the API call to the service.
// the "output" return value is not valid until after CreateVoiceTaskCommon Send returns without error.
//
// See CreateVoiceTask for more information on using the CreateVoiceTask
// API call, and error handling.
//
//    // Example sending a request using the CreateVoiceTaskRequest method.
//    req, resp := client.CreateVoiceTaskRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *VS) CreateVoiceTaskRequest(input *CreateVoiceTaskInput) (req *request.Request, output *CreateVoiceTaskOutput) {
	op := &request.Operation{
		Name:       opCreateVoiceTask,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &CreateVoiceTaskInput{}
	}

	output = &CreateVoiceTaskOutput{}
	req = c.newRequest(op, input, output)

	req.HTTPRequest.Header.Set("Content-Type", "application/json; charset=utf-8")

	return
}

// CreateVoiceTask API operation for VS.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for VS's
// API operation CreateVoiceTask for usage and error information.
func (c *VS) CreateVoiceTask(input *CreateVoiceTaskInput) (*CreateVoiceTaskOutput, error) {
	req, out := c.CreateVoiceTaskRequest(input)
	return out, req.Send()
}

// CreateVoiceTaskWithContext is the same as CreateVoiceTask with the addition of
// the ability to pass a context and additional request options.
//
// See CreateVoiceTask for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *VS) CreateVoiceTaskWithContext(ctx byteplus.Context, input *CreateVoiceTaskInput, opts ...request.Option) (*CreateVoiceTaskOutput, error) {
	req, out := c.CreateVoiceTaskRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type CreateVoiceTaskInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	// DisplayNum is a required field
	DisplayNum *string `type:"string" json:",omitempty" required:"true"`

	MaxHangUpTime *int32 `type:"int32" json:",omitempty"`

	MaxRingTime *int32 `type:"int32" json:",omitempty"`

	NumberInfoList []*NumberInfoListForCreateVoiceTaskInput `type:"list"`

	RepeatingCount *int32 `type:"int32" json:",omitempty"`

	SendTime *string `type:"string" json:",omitempty"`

	// ServiceCode is a required field
	ServiceCode *string `type:"string" json:",omitempty" required:"true"`

	// TaskId is a required field
	TaskId *string `type:"string" json:",omitempty" required:"true"`

	// TaskName is a required field
	TaskName *string `type:"string" json:",omitempty" required:"true"`

	TimeZone *string `type:"string" json:",omitempty"`

	VoiceContent *VoiceContentForCreateVoiceTaskInput `type:"structure" json:",omitempty"`
}

// String returns the string representation
func (s CreateVoiceTaskInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateVoiceTaskInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *CreateVoiceTaskInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "CreateVoiceTaskInput"}
	if s.DisplayNum == nil {
		invalidParams.Add(request.NewErrParamRequired("DisplayNum"))
	}
	if s.ServiceCode == nil {
		invalidParams.Add(request.NewErrParamRequired("ServiceCode"))
	}
	if s.TaskId == nil {
		invalidParams.Add(request.NewErrParamRequired("TaskId"))
	}
	if s.TaskName == nil {
		invalidParams.Add(request.NewErrParamRequired("TaskName"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetDisplayNum sets the DisplayNum field's value.
func (s *CreateVoiceTaskInput) SetDisplayNum(v string) *CreateVoiceTaskInput {
	s.DisplayNum = &v
	return s
}

// SetMaxHangUpTime sets the MaxHangUpTime field's value.
func (s *CreateVoiceTaskInput) SetMaxHangUpTime(v int32) *CreateVoiceTaskInput {
	s.MaxHangUpTime = &v
	return s
}

// SetMaxRingTime sets the MaxRingTime field's value.
func (s *CreateVoiceTaskInput) SetMaxRingTime(v int32) *CreateVoiceTaskInput {
	s.MaxRingTime = &v
	return s
}

// SetNumberInfoList sets the NumberInfoList field's value.
func (s *CreateVoiceTaskInput) SetNumberInfoList(v []*NumberInfoListForCreateVoiceTaskInput) *CreateVoiceTaskInput {
	s.NumberInfoList = v
	return s
}

// SetRepeatingCount sets the RepeatingCount field's value.
func (s *CreateVoiceTaskInput) SetRepeatingCount(v int32) *CreateVoiceTaskInput {
	s.RepeatingCount = &v
	return s
}

// SetSendTime sets the SendTime field's value.
func (s *CreateVoiceTaskInput) SetSendTime(v string) *CreateVoiceTaskInput {
	s.SendTime = &v
	return s
}

// SetServiceCode sets the ServiceCode field's value.
func (s *CreateVoiceTaskInput) SetServiceCode(v string) *CreateVoiceTaskInput {
	s.ServiceCode = &v
	return s
}

// SetTaskId sets the TaskId field's value.
func (s *CreateVoiceTaskInput) SetTaskId(v string) *CreateVoiceTaskInput {
	s.TaskId = &v
	return s
}

// SetTaskName sets the TaskName field's value.
func (s *CreateVoiceTaskInput) SetTaskName(v string) *CreateVoiceTaskInput {
	s.TaskName = &v
	return s
}

// SetTimeZone sets the TimeZone field's value.
func (s *CreateVoiceTaskInput) SetTimeZone(v string) *CreateVoiceTaskInput {
	s.TimeZone = &v
	return s
}

// SetVoiceContent sets the VoiceContent field's value.
func (s *CreateVoiceTaskInput) SetVoiceContent(v *VoiceContentForCreateVoiceTaskInput) *CreateVoiceTaskInput {
	s.VoiceContent = v
	return s
}

type CreateVoiceTaskOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	Metadata *response.ResponseMetadata

	Data *DataForCreateVoiceTaskOutput `type:"structure" json:",omitempty"`

	ErrorMessage *string `type:"string" json:",omitempty"`

	Result *string `type:"string" json:",omitempty"`
}

// String returns the string representation
func (s CreateVoiceTaskOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateVoiceTaskOutput) GoString() string {
	return s.String()
}

// SetData sets the Data field's value.
func (s *CreateVoiceTaskOutput) SetData(v *DataForCreateVoiceTaskOutput) *CreateVoiceTaskOutput {
	s.Data = v
	return s
}

// SetErrorMessage sets the ErrorMessage field's value.
func (s *CreateVoiceTaskOutput) SetErrorMessage(v string) *CreateVoiceTaskOutput {
	s.ErrorMessage = &v
	return s
}

// SetResult sets the Result field's value.
func (s *CreateVoiceTaskOutput) SetResult(v string) *CreateVoiceTaskOutput {
	s.Result = &v
	return s
}

type DataForCreateVoiceTaskOutput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	TaskId *string `type:"string" json:"taskId,omitempty"`
}

// String returns the string representation
func (s DataForCreateVoiceTaskOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s DataForCreateVoiceTaskOutput) GoString() string {
	return s.String()
}

// SetTaskId sets the TaskId field's value.
func (s *DataForCreateVoiceTaskOutput) SetTaskId(v string) *DataForCreateVoiceTaskOutput {
	s.TaskId = &v
	return s
}

type NumberInfoListForCreateVoiceTaskInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	CalleeNumber *string `type:"string" json:"calleeNumber,omitempty"`

	ParamObj *string `type:"string" json:"paramObj,omitempty"`
}

// String returns the string representation
func (s NumberInfoListForCreateVoiceTaskInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s NumberInfoListForCreateVoiceTaskInput) GoString() string {
	return s.String()
}

// SetCalleeNumber sets the CalleeNumber field's value.
func (s *NumberInfoListForCreateVoiceTaskInput) SetCalleeNumber(v string) *NumberInfoListForCreateVoiceTaskInput {
	s.CalleeNumber = &v
	return s
}

// SetParamObj sets the ParamObj field's value.
func (s *NumberInfoListForCreateVoiceTaskInput) SetParamObj(v string) *NumberInfoListForCreateVoiceTaskInput {
	s.ParamObj = &v
	return s
}

type VoiceContentForCreateVoiceTaskInput struct {
	_ struct{} `type:"structure" json:",omitempty"`

	BaseFile *string `type:"string" json:"baseFile,omitempty"`

	FileName *string `type:"string" json:"fileName,omitempty"`

	Source *int32 `type:"int32" json:"source,omitempty"`

	Text *string `type:"string" json:"text,omitempty"`

	TtsLanguage *string `type:"string" json:"ttsLanguage,omitempty"`

	TtsSpeed *int32 `type:"int32" json:"ttsSpeed,omitempty"`

	VoiceId *string `type:"string" json:"voiceId,omitempty"`
}

// String returns the string representation
func (s VoiceContentForCreateVoiceTaskInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s VoiceContentForCreateVoiceTaskInput) GoString() string {
	return s.String()
}

// SetBaseFile sets the BaseFile field's value.
func (s *VoiceContentForCreateVoiceTaskInput) SetBaseFile(v string) *VoiceContentForCreateVoiceTaskInput {
	s.BaseFile = &v
	return s
}

// SetFileName sets the FileName field's value.
func (s *VoiceContentForCreateVoiceTaskInput) SetFileName(v string) *VoiceContentForCreateVoiceTaskInput {
	s.FileName = &v
	return s
}

// SetSource sets the Source field's value.
func (s *VoiceContentForCreateVoiceTaskInput) SetSource(v int32) *VoiceContentForCreateVoiceTaskInput {
	s.Source = &v
	return s
}

// SetText sets the Text field's value.
func (s *VoiceContentForCreateVoiceTaskInput) SetText(v string) *VoiceContentForCreateVoiceTaskInput {
	s.Text = &v
	return s
}

// SetTtsLanguage sets the TtsLanguage field's value.
func (s *VoiceContentForCreateVoiceTaskInput) SetTtsLanguage(v string) *VoiceContentForCreateVoiceTaskInput {
	s.TtsLanguage = &v
	return s
}

// SetTtsSpeed sets the TtsSpeed field's value.
func (s *VoiceContentForCreateVoiceTaskInput) SetTtsSpeed(v int32) *VoiceContentForCreateVoiceTaskInput {
	s.TtsSpeed = &v
	return s
}

// SetVoiceId sets the VoiceId field's value.
func (s *VoiceContentForCreateVoiceTaskInput) SetVoiceId(v string) *VoiceContentForCreateVoiceTaskInput {
	s.VoiceId = &v
	return s
}
