// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

package natgateway

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/byteplusutil"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/response"
)

const opModifySessionLogCommon = "ModifySessionLog"

// ModifySessionLogCommonRequest generates a "byteplus/request.Request" representing the
// client's request for the ModifySessionLogCommon operation. The "output" return
// value will be populated with the ModifySessionLogCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ModifySessionLogCommon Request to send the API call to the service.
// the "output" return value is not valid until after ModifySessionLogCommon Send returns without error.
//
// See ModifySessionLogCommon for more information on using the ModifySessionLogCommon
// API call, and error handling.
//
//    // Example sending a request using the ModifySessionLogCommonRequest method.
//    req, resp := client.ModifySessionLogCommonRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *NATGATEWAY) ModifySessionLogCommonRequest(input *map[string]interface{}) (req *request.Request, output *map[string]interface{}) {
	op := &request.Operation{
		Name:       opModifySessionLogCommon,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &map[string]interface{}{}
	}

	output = &map[string]interface{}{}
	req = c.newRequest(op, input, output)

	return
}

// ModifySessionLogCommon API operation for NATGATEWAY.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for NATGATEWAY's
// API operation ModifySessionLogCommon for usage and error information.
func (c *NATGATEWAY) ModifySessionLogCommon(input *map[string]interface{}) (*map[string]interface{}, error) {
	req, out := c.ModifySessionLogCommonRequest(input)
	return out, req.Send()
}

// ModifySessionLogCommonWithContext is the same as ModifySessionLogCommon with the addition of
// the ability to pass a context and additional request options.
//
// See ModifySessionLogCommon for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If the context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *NATGATEWAY) ModifySessionLogCommonWithContext(ctx byteplus.Context, input *map[string]interface{}, opts ...request.Option) (*map[string]interface{}, error) {
	req, out := c.ModifySessionLogCommonRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opModifySessionLog = "ModifySessionLog"

// ModifySessionLogRequest generates a "byteplus/request.Request" representing the
// client's request for the ModifySessionLog operation. The "output" return
// value will be populated with the ModifySessionLogCommon request's response once the request completes
// successfully.
//
// Use "Send" method on the returned ModifySessionLogCommon Request to send the API call to the service.
// the "output" return value is not valid until after ModifySessionLogCommon Send returns without error.
//
// See ModifySessionLog for more information on using the ModifySessionLog
// API call, and error handling.
//
//    // Example sending a request using the ModifySessionLogRequest method.
//    req, resp := client.ModifySessionLogRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *NATGATEWAY) ModifySessionLogRequest(input *ModifySessionLogInput) (req *request.Request, output *ModifySessionLogOutput) {
	op := &request.Operation{
		Name:       opModifySessionLog,
		HTTPMethod: "GET",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ModifySessionLogInput{}
	}

	output = &ModifySessionLogOutput{}
	req = c.newRequest(op, input, output)

	return
}

// ModifySessionLog API operation for NATGATEWAY.
//
// Returns bytepluserr.Error for service API and SDK errors. Use runtime type assertions
// with bytepluserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the BYTEPLUS API reference guide for NATGATEWAY's
// API operation ModifySessionLog for usage and error information.
func (c *NATGATEWAY) ModifySessionLog(input *ModifySessionLogInput) (*ModifySessionLogOutput, error) {
	req, out := c.ModifySessionLogRequest(input)
	return out, req.Send()
}

// ModifySessionLogWithContext is the same as ModifySessionLog with the addition of
// the ability to pass a context and additional request options.
//
// See ModifySessionLog for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. Ifthe context is nil a panic will occur.
// In the future the SDK may create sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *NATGATEWAY) ModifySessionLogWithContext(ctx byteplus.Context, input *ModifySessionLogInput, opts ...request.Option) (*ModifySessionLogOutput, error) {
	req, out := c.ModifySessionLogRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

type ModifySessionLogInput struct {
	_ struct{} `type:"structure"`

	Description *string `type:"string"`

	// SessionLogId is a required field
	SessionLogId *string `type:"string" required:"true"`

	SessionLogName *string `type:"string"`
}

// String returns the string representation
func (s ModifySessionLogInput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ModifySessionLogInput) GoString() string {
	return s.String()
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *ModifySessionLogInput) Validate() error {
	invalidParams := request.ErrInvalidParams{Context: "ModifySessionLogInput"}
	if s.SessionLogId == nil {
		invalidParams.Add(request.NewErrParamRequired("SessionLogId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// SetDescription sets the Description field's value.
func (s *ModifySessionLogInput) SetDescription(v string) *ModifySessionLogInput {
	s.Description = &v
	return s
}

// SetSessionLogId sets the SessionLogId field's value.
func (s *ModifySessionLogInput) SetSessionLogId(v string) *ModifySessionLogInput {
	s.SessionLogId = &v
	return s
}

// SetSessionLogName sets the SessionLogName field's value.
func (s *ModifySessionLogInput) SetSessionLogName(v string) *ModifySessionLogInput {
	s.SessionLogName = &v
	return s
}

type ModifySessionLogOutput struct {
	_ struct{} `type:"structure"`

	Metadata *response.ResponseMetadata

	RequestId *string `type:"string"`
}

// String returns the string representation
func (s ModifySessionLogOutput) String() string {
	return byteplusutil.Prettify(s)
}

// GoString returns the string representation
func (s ModifySessionLogOutput) GoString() string {
	return s.String()
}

// SetRequestId sets the RequestId field's value.
func (s *ModifySessionLogOutput) SetRequestId(v string) *ModifySessionLogOutput {
	s.RequestId = &v
	return s
}
