// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package privatelinkiface provides an interface to enable mocking the PRIVATELINK service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package privatelink

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
)

// PRIVATELINKAPI provides an interface to enable mocking the
// privatelink.PRIVATELINK service client's API operation,
//
//    // byteplus sdk func uses an SDK service client to make a request to
//    // PRIVATELINK.
//    func myFunc(svc PRIVATELINKAPI) bool {
//        // Make svc.AddPermissionToVpcEndpointService request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := privatelink.New(sess)
//
//        myFunc(svc)
//    }
//
type PRIVATELINKAPI interface {
	AddPermissionToVpcEndpointServiceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	AddPermissionToVpcEndpointServiceCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AddPermissionToVpcEndpointServiceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AddPermissionToVpcEndpointService(*AddPermissionToVpcEndpointServiceInput) (*AddPermissionToVpcEndpointServiceOutput, error)
	AddPermissionToVpcEndpointServiceWithContext(byteplus.Context, *AddPermissionToVpcEndpointServiceInput, ...request.Option) (*AddPermissionToVpcEndpointServiceOutput, error)
	AddPermissionToVpcEndpointServiceRequest(*AddPermissionToVpcEndpointServiceInput) (*request.Request, *AddPermissionToVpcEndpointServiceOutput)

	AddZoneToVpcEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	AddZoneToVpcEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AddZoneToVpcEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AddZoneToVpcEndpoint(*AddZoneToVpcEndpointInput) (*AddZoneToVpcEndpointOutput, error)
	AddZoneToVpcEndpointWithContext(byteplus.Context, *AddZoneToVpcEndpointInput, ...request.Option) (*AddZoneToVpcEndpointOutput, error)
	AddZoneToVpcEndpointRequest(*AddZoneToVpcEndpointInput) (*request.Request, *AddZoneToVpcEndpointOutput)

	AttachResourceToVpcEndpointServiceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	AttachResourceToVpcEndpointServiceCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AttachResourceToVpcEndpointServiceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AttachResourceToVpcEndpointService(*AttachResourceToVpcEndpointServiceInput) (*AttachResourceToVpcEndpointServiceOutput, error)
	AttachResourceToVpcEndpointServiceWithContext(byteplus.Context, *AttachResourceToVpcEndpointServiceInput, ...request.Option) (*AttachResourceToVpcEndpointServiceOutput, error)
	AttachResourceToVpcEndpointServiceRequest(*AttachResourceToVpcEndpointServiceInput) (*request.Request, *AttachResourceToVpcEndpointServiceOutput)

	AttachSecurityGroupToVpcEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	AttachSecurityGroupToVpcEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AttachSecurityGroupToVpcEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AttachSecurityGroupToVpcEndpoint(*AttachSecurityGroupToVpcEndpointInput) (*AttachSecurityGroupToVpcEndpointOutput, error)
	AttachSecurityGroupToVpcEndpointWithContext(byteplus.Context, *AttachSecurityGroupToVpcEndpointInput, ...request.Option) (*AttachSecurityGroupToVpcEndpointOutput, error)
	AttachSecurityGroupToVpcEndpointRequest(*AttachSecurityGroupToVpcEndpointInput) (*request.Request, *AttachSecurityGroupToVpcEndpointOutput)

	CreateUniqueResourceTypeVpcEndpointServiceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateUniqueResourceTypeVpcEndpointServiceCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateUniqueResourceTypeVpcEndpointServiceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateUniqueResourceTypeVpcEndpointService(*CreateUniqueResourceTypeVpcEndpointServiceInput) (*CreateUniqueResourceTypeVpcEndpointServiceOutput, error)
	CreateUniqueResourceTypeVpcEndpointServiceWithContext(byteplus.Context, *CreateUniqueResourceTypeVpcEndpointServiceInput, ...request.Option) (*CreateUniqueResourceTypeVpcEndpointServiceOutput, error)
	CreateUniqueResourceTypeVpcEndpointServiceRequest(*CreateUniqueResourceTypeVpcEndpointServiceInput) (*request.Request, *CreateUniqueResourceTypeVpcEndpointServiceOutput)

	CreateVpcEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateVpcEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateVpcEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateVpcEndpoint(*CreateVpcEndpointInput) (*CreateVpcEndpointOutput, error)
	CreateVpcEndpointWithContext(byteplus.Context, *CreateVpcEndpointInput, ...request.Option) (*CreateVpcEndpointOutput, error)
	CreateVpcEndpointRequest(*CreateVpcEndpointInput) (*request.Request, *CreateVpcEndpointOutput)

	CreateVpcEndpointServiceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateVpcEndpointServiceCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateVpcEndpointServiceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateVpcEndpointService(*CreateVpcEndpointServiceInput) (*CreateVpcEndpointServiceOutput, error)
	CreateVpcEndpointServiceWithContext(byteplus.Context, *CreateVpcEndpointServiceInput, ...request.Option) (*CreateVpcEndpointServiceOutput, error)
	CreateVpcEndpointServiceRequest(*CreateVpcEndpointServiceInput) (*request.Request, *CreateVpcEndpointServiceOutput)

	CreateVpcGatewayEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateVpcGatewayEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateVpcGatewayEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateVpcGatewayEndpoint(*CreateVpcGatewayEndpointInput) (*CreateVpcGatewayEndpointOutput, error)
	CreateVpcGatewayEndpointWithContext(byteplus.Context, *CreateVpcGatewayEndpointInput, ...request.Option) (*CreateVpcGatewayEndpointOutput, error)
	CreateVpcGatewayEndpointRequest(*CreateVpcGatewayEndpointInput) (*request.Request, *CreateVpcGatewayEndpointOutput)

	DeleteVpcEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteVpcEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteVpcEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteVpcEndpoint(*DeleteVpcEndpointInput) (*DeleteVpcEndpointOutput, error)
	DeleteVpcEndpointWithContext(byteplus.Context, *DeleteVpcEndpointInput, ...request.Option) (*DeleteVpcEndpointOutput, error)
	DeleteVpcEndpointRequest(*DeleteVpcEndpointInput) (*request.Request, *DeleteVpcEndpointOutput)

	DeleteVpcEndpointServiceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteVpcEndpointServiceCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteVpcEndpointServiceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteVpcEndpointService(*DeleteVpcEndpointServiceInput) (*DeleteVpcEndpointServiceOutput, error)
	DeleteVpcEndpointServiceWithContext(byteplus.Context, *DeleteVpcEndpointServiceInput, ...request.Option) (*DeleteVpcEndpointServiceOutput, error)
	DeleteVpcEndpointServiceRequest(*DeleteVpcEndpointServiceInput) (*request.Request, *DeleteVpcEndpointServiceOutput)

	DeleteVpcGatewayEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteVpcGatewayEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteVpcGatewayEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteVpcGatewayEndpoint(*DeleteVpcGatewayEndpointInput) (*DeleteVpcGatewayEndpointOutput, error)
	DeleteVpcGatewayEndpointWithContext(byteplus.Context, *DeleteVpcGatewayEndpointInput, ...request.Option) (*DeleteVpcGatewayEndpointOutput, error)
	DeleteVpcGatewayEndpointRequest(*DeleteVpcGatewayEndpointInput) (*request.Request, *DeleteVpcGatewayEndpointOutput)

	DescribeCrossRegionSupportedRegionsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeCrossRegionSupportedRegionsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeCrossRegionSupportedRegionsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeCrossRegionSupportedRegions(*DescribeCrossRegionSupportedRegionsInput) (*DescribeCrossRegionSupportedRegionsOutput, error)
	DescribeCrossRegionSupportedRegionsWithContext(byteplus.Context, *DescribeCrossRegionSupportedRegionsInput, ...request.Option) (*DescribeCrossRegionSupportedRegionsOutput, error)
	DescribeCrossRegionSupportedRegionsRequest(*DescribeCrossRegionSupportedRegionsInput) (*request.Request, *DescribeCrossRegionSupportedRegionsOutput)

	DescribeCrossRegionSupportedZonesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeCrossRegionSupportedZonesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeCrossRegionSupportedZonesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeCrossRegionSupportedZones(*DescribeCrossRegionSupportedZonesInput) (*DescribeCrossRegionSupportedZonesOutput, error)
	DescribeCrossRegionSupportedZonesWithContext(byteplus.Context, *DescribeCrossRegionSupportedZonesInput, ...request.Option) (*DescribeCrossRegionSupportedZonesOutput, error)
	DescribeCrossRegionSupportedZonesRequest(*DescribeCrossRegionSupportedZonesInput) (*request.Request, *DescribeCrossRegionSupportedZonesOutput)

	DescribePrivateLinkAvailableZonesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribePrivateLinkAvailableZonesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribePrivateLinkAvailableZonesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribePrivateLinkAvailableZones(*DescribePrivateLinkAvailableZonesInput) (*DescribePrivateLinkAvailableZonesOutput, error)
	DescribePrivateLinkAvailableZonesWithContext(byteplus.Context, *DescribePrivateLinkAvailableZonesInput, ...request.Option) (*DescribePrivateLinkAvailableZonesOutput, error)
	DescribePrivateLinkAvailableZonesRequest(*DescribePrivateLinkAvailableZonesInput) (*request.Request, *DescribePrivateLinkAvailableZonesOutput)

	DescribeVpcEndpointAttributesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcEndpointAttributesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcEndpointAttributesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcEndpointAttributes(*DescribeVpcEndpointAttributesInput) (*DescribeVpcEndpointAttributesOutput, error)
	DescribeVpcEndpointAttributesWithContext(byteplus.Context, *DescribeVpcEndpointAttributesInput, ...request.Option) (*DescribeVpcEndpointAttributesOutput, error)
	DescribeVpcEndpointAttributesRequest(*DescribeVpcEndpointAttributesInput) (*request.Request, *DescribeVpcEndpointAttributesOutput)

	DescribeVpcEndpointConnectionsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcEndpointConnectionsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcEndpointConnectionsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcEndpointConnections(*DescribeVpcEndpointConnectionsInput) (*DescribeVpcEndpointConnectionsOutput, error)
	DescribeVpcEndpointConnectionsWithContext(byteplus.Context, *DescribeVpcEndpointConnectionsInput, ...request.Option) (*DescribeVpcEndpointConnectionsOutput, error)
	DescribeVpcEndpointConnectionsRequest(*DescribeVpcEndpointConnectionsInput) (*request.Request, *DescribeVpcEndpointConnectionsOutput)

	DescribeVpcEndpointSecurityGroupsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcEndpointSecurityGroupsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcEndpointSecurityGroupsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcEndpointSecurityGroups(*DescribeVpcEndpointSecurityGroupsInput) (*DescribeVpcEndpointSecurityGroupsOutput, error)
	DescribeVpcEndpointSecurityGroupsWithContext(byteplus.Context, *DescribeVpcEndpointSecurityGroupsInput, ...request.Option) (*DescribeVpcEndpointSecurityGroupsOutput, error)
	DescribeVpcEndpointSecurityGroupsRequest(*DescribeVpcEndpointSecurityGroupsInput) (*request.Request, *DescribeVpcEndpointSecurityGroupsOutput)

	DescribeVpcEndpointServiceAttributesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcEndpointServiceAttributesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcEndpointServiceAttributesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcEndpointServiceAttributes(*DescribeVpcEndpointServiceAttributesInput) (*DescribeVpcEndpointServiceAttributesOutput, error)
	DescribeVpcEndpointServiceAttributesWithContext(byteplus.Context, *DescribeVpcEndpointServiceAttributesInput, ...request.Option) (*DescribeVpcEndpointServiceAttributesOutput, error)
	DescribeVpcEndpointServiceAttributesRequest(*DescribeVpcEndpointServiceAttributesInput) (*request.Request, *DescribeVpcEndpointServiceAttributesOutput)

	DescribeVpcEndpointServicePermissionsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcEndpointServicePermissionsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcEndpointServicePermissionsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcEndpointServicePermissions(*DescribeVpcEndpointServicePermissionsInput) (*DescribeVpcEndpointServicePermissionsOutput, error)
	DescribeVpcEndpointServicePermissionsWithContext(byteplus.Context, *DescribeVpcEndpointServicePermissionsInput, ...request.Option) (*DescribeVpcEndpointServicePermissionsOutput, error)
	DescribeVpcEndpointServicePermissionsRequest(*DescribeVpcEndpointServicePermissionsInput) (*request.Request, *DescribeVpcEndpointServicePermissionsOutput)

	DescribeVpcEndpointServiceResourcesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcEndpointServiceResourcesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcEndpointServiceResourcesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcEndpointServiceResources(*DescribeVpcEndpointServiceResourcesInput) (*DescribeVpcEndpointServiceResourcesOutput, error)
	DescribeVpcEndpointServiceResourcesWithContext(byteplus.Context, *DescribeVpcEndpointServiceResourcesInput, ...request.Option) (*DescribeVpcEndpointServiceResourcesOutput, error)
	DescribeVpcEndpointServiceResourcesRequest(*DescribeVpcEndpointServiceResourcesInput) (*request.Request, *DescribeVpcEndpointServiceResourcesOutput)

	DescribeVpcEndpointServicesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcEndpointServicesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcEndpointServicesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcEndpointServices(*DescribeVpcEndpointServicesInput) (*DescribeVpcEndpointServicesOutput, error)
	DescribeVpcEndpointServicesWithContext(byteplus.Context, *DescribeVpcEndpointServicesInput, ...request.Option) (*DescribeVpcEndpointServicesOutput, error)
	DescribeVpcEndpointServicesRequest(*DescribeVpcEndpointServicesInput) (*request.Request, *DescribeVpcEndpointServicesOutput)

	DescribeVpcEndpointServicesByEndUserCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcEndpointServicesByEndUserCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcEndpointServicesByEndUserCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcEndpointServicesByEndUser(*DescribeVpcEndpointServicesByEndUserInput) (*DescribeVpcEndpointServicesByEndUserOutput, error)
	DescribeVpcEndpointServicesByEndUserWithContext(byteplus.Context, *DescribeVpcEndpointServicesByEndUserInput, ...request.Option) (*DescribeVpcEndpointServicesByEndUserOutput, error)
	DescribeVpcEndpointServicesByEndUserRequest(*DescribeVpcEndpointServicesByEndUserInput) (*request.Request, *DescribeVpcEndpointServicesByEndUserOutput)

	DescribeVpcEndpointZonesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcEndpointZonesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcEndpointZonesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcEndpointZones(*DescribeVpcEndpointZonesInput) (*DescribeVpcEndpointZonesOutput, error)
	DescribeVpcEndpointZonesWithContext(byteplus.Context, *DescribeVpcEndpointZonesInput, ...request.Option) (*DescribeVpcEndpointZonesOutput, error)
	DescribeVpcEndpointZonesRequest(*DescribeVpcEndpointZonesInput) (*request.Request, *DescribeVpcEndpointZonesOutput)

	DescribeVpcEndpointsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcEndpointsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcEndpointsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcEndpoints(*DescribeVpcEndpointsInput) (*DescribeVpcEndpointsOutput, error)
	DescribeVpcEndpointsWithContext(byteplus.Context, *DescribeVpcEndpointsInput, ...request.Option) (*DescribeVpcEndpointsOutput, error)
	DescribeVpcEndpointsRequest(*DescribeVpcEndpointsInput) (*request.Request, *DescribeVpcEndpointsOutput)

	DescribeVpcGatewayEndpointAttributesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcGatewayEndpointAttributesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcGatewayEndpointAttributesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcGatewayEndpointAttributes(*DescribeVpcGatewayEndpointAttributesInput) (*DescribeVpcGatewayEndpointAttributesOutput, error)
	DescribeVpcGatewayEndpointAttributesWithContext(byteplus.Context, *DescribeVpcGatewayEndpointAttributesInput, ...request.Option) (*DescribeVpcGatewayEndpointAttributesOutput, error)
	DescribeVpcGatewayEndpointAttributesRequest(*DescribeVpcGatewayEndpointAttributesInput) (*request.Request, *DescribeVpcGatewayEndpointAttributesOutput)

	DescribeVpcGatewayEndpointServicesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcGatewayEndpointServicesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcGatewayEndpointServicesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcGatewayEndpointServices(*DescribeVpcGatewayEndpointServicesInput) (*DescribeVpcGatewayEndpointServicesOutput, error)
	DescribeVpcGatewayEndpointServicesWithContext(byteplus.Context, *DescribeVpcGatewayEndpointServicesInput, ...request.Option) (*DescribeVpcGatewayEndpointServicesOutput, error)
	DescribeVpcGatewayEndpointServicesRequest(*DescribeVpcGatewayEndpointServicesInput) (*request.Request, *DescribeVpcGatewayEndpointServicesOutput)

	DescribeVpcGatewayEndpointsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeVpcGatewayEndpointsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeVpcGatewayEndpointsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeVpcGatewayEndpoints(*DescribeVpcGatewayEndpointsInput) (*DescribeVpcGatewayEndpointsOutput, error)
	DescribeVpcGatewayEndpointsWithContext(byteplus.Context, *DescribeVpcGatewayEndpointsInput, ...request.Option) (*DescribeVpcGatewayEndpointsOutput, error)
	DescribeVpcGatewayEndpointsRequest(*DescribeVpcGatewayEndpointsInput) (*request.Request, *DescribeVpcGatewayEndpointsOutput)

	DetachResourceFromVpcEndpointServiceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DetachResourceFromVpcEndpointServiceCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DetachResourceFromVpcEndpointServiceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DetachResourceFromVpcEndpointService(*DetachResourceFromVpcEndpointServiceInput) (*DetachResourceFromVpcEndpointServiceOutput, error)
	DetachResourceFromVpcEndpointServiceWithContext(byteplus.Context, *DetachResourceFromVpcEndpointServiceInput, ...request.Option) (*DetachResourceFromVpcEndpointServiceOutput, error)
	DetachResourceFromVpcEndpointServiceRequest(*DetachResourceFromVpcEndpointServiceInput) (*request.Request, *DetachResourceFromVpcEndpointServiceOutput)

	DetachSecurityGroupFromVpcEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DetachSecurityGroupFromVpcEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DetachSecurityGroupFromVpcEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DetachSecurityGroupFromVpcEndpoint(*DetachSecurityGroupFromVpcEndpointInput) (*DetachSecurityGroupFromVpcEndpointOutput, error)
	DetachSecurityGroupFromVpcEndpointWithContext(byteplus.Context, *DetachSecurityGroupFromVpcEndpointInput, ...request.Option) (*DetachSecurityGroupFromVpcEndpointOutput, error)
	DetachSecurityGroupFromVpcEndpointRequest(*DetachSecurityGroupFromVpcEndpointInput) (*request.Request, *DetachSecurityGroupFromVpcEndpointOutput)

	DisableVpcEndpointConnectionCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DisableVpcEndpointConnectionCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DisableVpcEndpointConnectionCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DisableVpcEndpointConnection(*DisableVpcEndpointConnectionInput) (*DisableVpcEndpointConnectionOutput, error)
	DisableVpcEndpointConnectionWithContext(byteplus.Context, *DisableVpcEndpointConnectionInput, ...request.Option) (*DisableVpcEndpointConnectionOutput, error)
	DisableVpcEndpointConnectionRequest(*DisableVpcEndpointConnectionInput) (*request.Request, *DisableVpcEndpointConnectionOutput)

	EnableVpcEndpointConnectionCommon(*map[string]interface{}) (*map[string]interface{}, error)
	EnableVpcEndpointConnectionCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	EnableVpcEndpointConnectionCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	EnableVpcEndpointConnection(*EnableVpcEndpointConnectionInput) (*EnableVpcEndpointConnectionOutput, error)
	EnableVpcEndpointConnectionWithContext(byteplus.Context, *EnableVpcEndpointConnectionInput, ...request.Option) (*EnableVpcEndpointConnectionOutput, error)
	EnableVpcEndpointConnectionRequest(*EnableVpcEndpointConnectionInput) (*request.Request, *EnableVpcEndpointConnectionOutput)

	ListTagsForResourcesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListTagsForResourcesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListTagsForResourcesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListTagsForResources(*ListTagsForResourcesInput) (*ListTagsForResourcesOutput, error)
	ListTagsForResourcesWithContext(byteplus.Context, *ListTagsForResourcesInput, ...request.Option) (*ListTagsForResourcesOutput, error)
	ListTagsForResourcesRequest(*ListTagsForResourcesInput) (*request.Request, *ListTagsForResourcesOutput)

	ModifyEndpointPayerAccountCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyEndpointPayerAccountCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyEndpointPayerAccountCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyEndpointPayerAccount(*ModifyEndpointPayerAccountInput) (*ModifyEndpointPayerAccountOutput, error)
	ModifyEndpointPayerAccountWithContext(byteplus.Context, *ModifyEndpointPayerAccountInput, ...request.Option) (*ModifyEndpointPayerAccountOutput, error)
	ModifyEndpointPayerAccountRequest(*ModifyEndpointPayerAccountInput) (*request.Request, *ModifyEndpointPayerAccountOutput)

	ModifyUniqueResourceTypeVpcEndpointServiceAttributesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyUniqueResourceTypeVpcEndpointServiceAttributesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyUniqueResourceTypeVpcEndpointServiceAttributesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyUniqueResourceTypeVpcEndpointServiceAttributes(*ModifyUniqueResourceTypeVpcEndpointServiceAttributesInput) (*ModifyUniqueResourceTypeVpcEndpointServiceAttributesOutput, error)
	ModifyUniqueResourceTypeVpcEndpointServiceAttributesWithContext(byteplus.Context, *ModifyUniqueResourceTypeVpcEndpointServiceAttributesInput, ...request.Option) (*ModifyUniqueResourceTypeVpcEndpointServiceAttributesOutput, error)
	ModifyUniqueResourceTypeVpcEndpointServiceAttributesRequest(*ModifyUniqueResourceTypeVpcEndpointServiceAttributesInput) (*request.Request, *ModifyUniqueResourceTypeVpcEndpointServiceAttributesOutput)

	ModifyVpcEndpointAttributesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyVpcEndpointAttributesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyVpcEndpointAttributesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyVpcEndpointAttributes(*ModifyVpcEndpointAttributesInput) (*ModifyVpcEndpointAttributesOutput, error)
	ModifyVpcEndpointAttributesWithContext(byteplus.Context, *ModifyVpcEndpointAttributesInput, ...request.Option) (*ModifyVpcEndpointAttributesOutput, error)
	ModifyVpcEndpointAttributesRequest(*ModifyVpcEndpointAttributesInput) (*request.Request, *ModifyVpcEndpointAttributesOutput)

	ModifyVpcEndpointConnectionsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyVpcEndpointConnectionsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyVpcEndpointConnectionsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyVpcEndpointConnections(*ModifyVpcEndpointConnectionsInput) (*ModifyVpcEndpointConnectionsOutput, error)
	ModifyVpcEndpointConnectionsWithContext(byteplus.Context, *ModifyVpcEndpointConnectionsInput, ...request.Option) (*ModifyVpcEndpointConnectionsOutput, error)
	ModifyVpcEndpointConnectionsRequest(*ModifyVpcEndpointConnectionsInput) (*request.Request, *ModifyVpcEndpointConnectionsOutput)

	ModifyVpcEndpointServiceAttributesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyVpcEndpointServiceAttributesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyVpcEndpointServiceAttributesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyVpcEndpointServiceAttributes(*ModifyVpcEndpointServiceAttributesInput) (*ModifyVpcEndpointServiceAttributesOutput, error)
	ModifyVpcEndpointServiceAttributesWithContext(byteplus.Context, *ModifyVpcEndpointServiceAttributesInput, ...request.Option) (*ModifyVpcEndpointServiceAttributesOutput, error)
	ModifyVpcEndpointServiceAttributesRequest(*ModifyVpcEndpointServiceAttributesInput) (*request.Request, *ModifyVpcEndpointServiceAttributesOutput)

	ModifyVpcEndpointServiceResourceAttributesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyVpcEndpointServiceResourceAttributesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyVpcEndpointServiceResourceAttributesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyVpcEndpointServiceResourceAttributes(*ModifyVpcEndpointServiceResourceAttributesInput) (*ModifyVpcEndpointServiceResourceAttributesOutput, error)
	ModifyVpcEndpointServiceResourceAttributesWithContext(byteplus.Context, *ModifyVpcEndpointServiceResourceAttributesInput, ...request.Option) (*ModifyVpcEndpointServiceResourceAttributesOutput, error)
	ModifyVpcEndpointServiceResourceAttributesRequest(*ModifyVpcEndpointServiceResourceAttributesInput) (*request.Request, *ModifyVpcEndpointServiceResourceAttributesOutput)

	ModifyVpcEndpointZoneConnectionResourceAttributesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyVpcEndpointZoneConnectionResourceAttributesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyVpcEndpointZoneConnectionResourceAttributesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyVpcEndpointZoneConnectionResourceAttributes(*ModifyVpcEndpointZoneConnectionResourceAttributesInput) (*ModifyVpcEndpointZoneConnectionResourceAttributesOutput, error)
	ModifyVpcEndpointZoneConnectionResourceAttributesWithContext(byteplus.Context, *ModifyVpcEndpointZoneConnectionResourceAttributesInput, ...request.Option) (*ModifyVpcEndpointZoneConnectionResourceAttributesOutput, error)
	ModifyVpcEndpointZoneConnectionResourceAttributesRequest(*ModifyVpcEndpointZoneConnectionResourceAttributesInput) (*request.Request, *ModifyVpcEndpointZoneConnectionResourceAttributesOutput)

	ModifyVpcGatewayEndpointAttributesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ModifyVpcGatewayEndpointAttributesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ModifyVpcGatewayEndpointAttributesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ModifyVpcGatewayEndpointAttributes(*ModifyVpcGatewayEndpointAttributesInput) (*ModifyVpcGatewayEndpointAttributesOutput, error)
	ModifyVpcGatewayEndpointAttributesWithContext(byteplus.Context, *ModifyVpcGatewayEndpointAttributesInput, ...request.Option) (*ModifyVpcGatewayEndpointAttributesOutput, error)
	ModifyVpcGatewayEndpointAttributesRequest(*ModifyVpcGatewayEndpointAttributesInput) (*request.Request, *ModifyVpcGatewayEndpointAttributesOutput)

	RemovePermissionFromVpcEndpointServiceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	RemovePermissionFromVpcEndpointServiceCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	RemovePermissionFromVpcEndpointServiceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	RemovePermissionFromVpcEndpointService(*RemovePermissionFromVpcEndpointServiceInput) (*RemovePermissionFromVpcEndpointServiceOutput, error)
	RemovePermissionFromVpcEndpointServiceWithContext(byteplus.Context, *RemovePermissionFromVpcEndpointServiceInput, ...request.Option) (*RemovePermissionFromVpcEndpointServiceOutput, error)
	RemovePermissionFromVpcEndpointServiceRequest(*RemovePermissionFromVpcEndpointServiceInput) (*request.Request, *RemovePermissionFromVpcEndpointServiceOutput)

	RemoveZoneFromVpcEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	RemoveZoneFromVpcEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	RemoveZoneFromVpcEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	RemoveZoneFromVpcEndpoint(*RemoveZoneFromVpcEndpointInput) (*RemoveZoneFromVpcEndpointOutput, error)
	RemoveZoneFromVpcEndpointWithContext(byteplus.Context, *RemoveZoneFromVpcEndpointInput, ...request.Option) (*RemoveZoneFromVpcEndpointOutput, error)
	RemoveZoneFromVpcEndpointRequest(*RemoveZoneFromVpcEndpointInput) (*request.Request, *RemoveZoneFromVpcEndpointOutput)

	TagResourcesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	TagResourcesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	TagResourcesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	TagResources(*TagResourcesInput) (*TagResourcesOutput, error)
	TagResourcesWithContext(byteplus.Context, *TagResourcesInput, ...request.Option) (*TagResourcesOutput, error)
	TagResourcesRequest(*TagResourcesInput) (*request.Request, *TagResourcesOutput)

	UntagResourcesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	UntagResourcesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UntagResourcesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UntagResources(*UntagResourcesInput) (*UntagResourcesOutput, error)
	UntagResourcesWithContext(byteplus.Context, *UntagResourcesInput, ...request.Option) (*UntagResourcesOutput, error)
	UntagResourcesRequest(*UntagResourcesInput) (*request.Request, *UntagResourcesOutput)

	VerifyVpcEndpointServicePrivateDNSCommon(*map[string]interface{}) (*map[string]interface{}, error)
	VerifyVpcEndpointServicePrivateDNSCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	VerifyVpcEndpointServicePrivateDNSCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	VerifyVpcEndpointServicePrivateDNS(*VerifyVpcEndpointServicePrivateDNSInput) (*VerifyVpcEndpointServicePrivateDNSOutput, error)
	VerifyVpcEndpointServicePrivateDNSWithContext(byteplus.Context, *VerifyVpcEndpointServicePrivateDNSInput, ...request.Option) (*VerifyVpcEndpointServicePrivateDNSOutput, error)
	VerifyVpcEndpointServicePrivateDNSRequest(*VerifyVpcEndpointServicePrivateDNSInput) (*request.Request, *VerifyVpcEndpointServicePrivateDNSOutput)
}

var _ PRIVATELINKAPI = (*PRIVATELINK)(nil)
