// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package resourceshareiface provides an interface to enable mocking the RESOURCE_SHARE service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package resourceshare

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
)

// RESOURCESHAREAPI provides an interface to enable mocking the
// resourceshare.RESOURCESHARE service client's API operation,
//
//    // byteplus sdk func uses an SDK service client to make a request to
//    // RESOURCE_SHARE.
//    func myFunc(svc RESOURCESHAREAPI) bool {
//        // Make svc.AcceptResourceShareInvitation request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := resourceshare.New(sess)
//
//        myFunc(svc)
//    }
//
type RESOURCESHAREAPI interface {
	AcceptResourceShareInvitationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	AcceptResourceShareInvitationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AcceptResourceShareInvitationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AcceptResourceShareInvitation(*AcceptResourceShareInvitationInput) (*AcceptResourceShareInvitationOutput, error)
	AcceptResourceShareInvitationWithContext(byteplus.Context, *AcceptResourceShareInvitationInput, ...request.Option) (*AcceptResourceShareInvitationOutput, error)
	AcceptResourceShareInvitationRequest(*AcceptResourceShareInvitationInput) (*request.Request, *AcceptResourceShareInvitationOutput)

	AssociateResourceShareCommon(*map[string]interface{}) (*map[string]interface{}, error)
	AssociateResourceShareCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	AssociateResourceShareCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	AssociateResourceShare(*AssociateResourceShareInput) (*AssociateResourceShareOutput, error)
	AssociateResourceShareWithContext(byteplus.Context, *AssociateResourceShareInput, ...request.Option) (*AssociateResourceShareOutput, error)
	AssociateResourceShareRequest(*AssociateResourceShareInput) (*request.Request, *AssociateResourceShareOutput)

	CreateResourceShareCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateResourceShareCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateResourceShareCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateResourceShare(*CreateResourceShareInput) (*CreateResourceShareOutput, error)
	CreateResourceShareWithContext(byteplus.Context, *CreateResourceShareInput, ...request.Option) (*CreateResourceShareOutput, error)
	CreateResourceShareRequest(*CreateResourceShareInput) (*request.Request, *CreateResourceShareOutput)

	DeleteResourceShareCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteResourceShareCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteResourceShareCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteResourceShare(*DeleteResourceShareInput) (*DeleteResourceShareOutput, error)
	DeleteResourceShareWithContext(byteplus.Context, *DeleteResourceShareInput, ...request.Option) (*DeleteResourceShareOutput, error)
	DeleteResourceShareRequest(*DeleteResourceShareInput) (*request.Request, *DeleteResourceShareOutput)

	DescribeResourceShareInvitationsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeResourceShareInvitationsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeResourceShareInvitationsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeResourceShareInvitations(*DescribeResourceShareInvitationsInput) (*DescribeResourceShareInvitationsOutput, error)
	DescribeResourceShareInvitationsWithContext(byteplus.Context, *DescribeResourceShareInvitationsInput, ...request.Option) (*DescribeResourceShareInvitationsOutput, error)
	DescribeResourceShareInvitationsRequest(*DescribeResourceShareInvitationsInput) (*request.Request, *DescribeResourceShareInvitationsOutput)

	DescribeResourceSharesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DescribeResourceSharesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DescribeResourceSharesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DescribeResourceShares(*DescribeResourceSharesInput) (*DescribeResourceSharesOutput, error)
	DescribeResourceSharesWithContext(byteplus.Context, *DescribeResourceSharesInput, ...request.Option) (*DescribeResourceSharesOutput, error)
	DescribeResourceSharesRequest(*DescribeResourceSharesInput) (*request.Request, *DescribeResourceSharesOutput)

	DisableSharingWithOrganizationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DisableSharingWithOrganizationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DisableSharingWithOrganizationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DisableSharingWithOrganization(*DisableSharingWithOrganizationInput) (*DisableSharingWithOrganizationOutput, error)
	DisableSharingWithOrganizationWithContext(byteplus.Context, *DisableSharingWithOrganizationInput, ...request.Option) (*DisableSharingWithOrganizationOutput, error)
	DisableSharingWithOrganizationRequest(*DisableSharingWithOrganizationInput) (*request.Request, *DisableSharingWithOrganizationOutput)

	DisassociateResourceShareCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DisassociateResourceShareCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DisassociateResourceShareCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DisassociateResourceShare(*DisassociateResourceShareInput) (*DisassociateResourceShareOutput, error)
	DisassociateResourceShareWithContext(byteplus.Context, *DisassociateResourceShareInput, ...request.Option) (*DisassociateResourceShareOutput, error)
	DisassociateResourceShareRequest(*DisassociateResourceShareInput) (*request.Request, *DisassociateResourceShareOutput)

	EnableSharingWithOrganizationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	EnableSharingWithOrganizationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	EnableSharingWithOrganizationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	EnableSharingWithOrganization(*EnableSharingWithOrganizationInput) (*EnableSharingWithOrganizationOutput, error)
	EnableSharingWithOrganizationWithContext(byteplus.Context, *EnableSharingWithOrganizationInput, ...request.Option) (*EnableSharingWithOrganizationOutput, error)
	EnableSharingWithOrganizationRequest(*EnableSharingWithOrganizationInput) (*request.Request, *EnableSharingWithOrganizationOutput)

	GetPermissionCommon(*map[string]interface{}) (*map[string]interface{}, error)
	GetPermissionCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetPermissionCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetPermission(*GetPermissionInput) (*GetPermissionOutput, error)
	GetPermissionWithContext(byteplus.Context, *GetPermissionInput, ...request.Option) (*GetPermissionOutput, error)
	GetPermissionRequest(*GetPermissionInput) (*request.Request, *GetPermissionOutput)

	ListPermissionsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListPermissionsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListPermissionsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListPermissions(*ListPermissionsInput) (*ListPermissionsOutput, error)
	ListPermissionsWithContext(byteplus.Context, *ListPermissionsInput, ...request.Option) (*ListPermissionsOutput, error)
	ListPermissionsRequest(*ListPermissionsInput) (*request.Request, *ListPermissionsOutput)

	ListPrincipalsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListPrincipalsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListPrincipalsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListPrincipals(*ListPrincipalsInput) (*ListPrincipalsOutput, error)
	ListPrincipalsWithContext(byteplus.Context, *ListPrincipalsInput, ...request.Option) (*ListPrincipalsOutput, error)
	ListPrincipalsRequest(*ListPrincipalsInput) (*request.Request, *ListPrincipalsOutput)

	ListResourceShareAssociationsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListResourceShareAssociationsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListResourceShareAssociationsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListResourceShareAssociations(*ListResourceShareAssociationsInput) (*ListResourceShareAssociationsOutput, error)
	ListResourceShareAssociationsWithContext(byteplus.Context, *ListResourceShareAssociationsInput, ...request.Option) (*ListResourceShareAssociationsOutput, error)
	ListResourceShareAssociationsRequest(*ListResourceShareAssociationsInput) (*request.Request, *ListResourceShareAssociationsOutput)

	ListResourceSharePermissionsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListResourceSharePermissionsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListResourceSharePermissionsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListResourceSharePermissions(*ListResourceSharePermissionsInput) (*ListResourceSharePermissionsOutput, error)
	ListResourceSharePermissionsWithContext(byteplus.Context, *ListResourceSharePermissionsInput, ...request.Option) (*ListResourceSharePermissionsOutput, error)
	ListResourceSharePermissionsRequest(*ListResourceSharePermissionsInput) (*request.Request, *ListResourceSharePermissionsOutput)

	ListResourceTypesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListResourceTypesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListResourceTypesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListResourceTypes(*ListResourceTypesInput) (*ListResourceTypesOutput, error)
	ListResourceTypesWithContext(byteplus.Context, *ListResourceTypesInput, ...request.Option) (*ListResourceTypesOutput, error)
	ListResourceTypesRequest(*ListResourceTypesInput) (*request.Request, *ListResourceTypesOutput)

	ListResourcesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListResourcesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListResourcesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListResources(*ListResourcesInput) (*ListResourcesOutput, error)
	ListResourcesWithContext(byteplus.Context, *ListResourcesInput, ...request.Option) (*ListResourcesOutput, error)
	ListResourcesRequest(*ListResourcesInput) (*request.Request, *ListResourcesOutput)

	ListTagsForResourcesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListTagsForResourcesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListTagsForResourcesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListTagsForResources(*ListTagsForResourcesInput) (*ListTagsForResourcesOutput, error)
	ListTagsForResourcesWithContext(byteplus.Context, *ListTagsForResourcesInput, ...request.Option) (*ListTagsForResourcesOutput, error)
	ListTagsForResourcesRequest(*ListTagsForResourcesInput) (*request.Request, *ListTagsForResourcesOutput)

	RejectResourceShareInvitationCommon(*map[string]interface{}) (*map[string]interface{}, error)
	RejectResourceShareInvitationCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	RejectResourceShareInvitationCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	RejectResourceShareInvitation(*RejectResourceShareInvitationInput) (*RejectResourceShareInvitationOutput, error)
	RejectResourceShareInvitationWithContext(byteplus.Context, *RejectResourceShareInvitationInput, ...request.Option) (*RejectResourceShareInvitationOutput, error)
	RejectResourceShareInvitationRequest(*RejectResourceShareInvitationInput) (*request.Request, *RejectResourceShareInvitationOutput)

	TagResourcesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	TagResourcesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	TagResourcesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	TagResources(*TagResourcesInput) (*TagResourcesOutput, error)
	TagResourcesWithContext(byteplus.Context, *TagResourcesInput, ...request.Option) (*TagResourcesOutput, error)
	TagResourcesRequest(*TagResourcesInput) (*request.Request, *TagResourcesOutput)

	UntagResourcesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	UntagResourcesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UntagResourcesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UntagResources(*UntagResourcesInput) (*UntagResourcesOutput, error)
	UntagResourcesWithContext(byteplus.Context, *UntagResourcesInput, ...request.Option) (*UntagResourcesOutput, error)
	UntagResourcesRequest(*UntagResourcesInput) (*request.Request, *UntagResourcesOutput)

	UpdateResourceShareCommon(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateResourceShareCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateResourceShareCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateResourceShare(*UpdateResourceShareInput) (*UpdateResourceShareOutput, error)
	UpdateResourceShareWithContext(byteplus.Context, *UpdateResourceShareInput, ...request.Option) (*UpdateResourceShareOutput, error)
	UpdateResourceShareRequest(*UpdateResourceShareInput) (*request.Request, *UpdateResourceShareOutput)
}

var _ RESOURCESHAREAPI = (*RESOURCESHARE)(nil)
