// Code generated by byteplus with private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package criface provides an interface to enable mocking the CR service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package cr

import (
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus"
	"github.com/byteplus-sdk/byteplus-go-sdk-v2/byteplus/request"
)

// CRAPI provides an interface to enable mocking the
// cr.CR service client's API operation,
//
//    // byteplus sdk func uses an SDK service client to make a request to
//    // CR.
//    func myFunc(svc CRAPI) bool {
//        // Make svc.CreateEndpointAclPolicies request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := cr.New(sess)
//
//        myFunc(svc)
//    }
//
type CRAPI interface {
	CreateEndpointAclPoliciesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateEndpointAclPoliciesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateEndpointAclPoliciesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateEndpointAclPolicies(*CreateEndpointAclPoliciesInput) (*CreateEndpointAclPoliciesOutput, error)
	CreateEndpointAclPoliciesWithContext(byteplus.Context, *CreateEndpointAclPoliciesInput, ...request.Option) (*CreateEndpointAclPoliciesOutput, error)
	CreateEndpointAclPoliciesRequest(*CreateEndpointAclPoliciesInput) (*request.Request, *CreateEndpointAclPoliciesOutput)

	CreateNamespaceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateNamespaceCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateNamespaceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateNamespace(*CreateNamespaceInput) (*CreateNamespaceOutput, error)
	CreateNamespaceWithContext(byteplus.Context, *CreateNamespaceInput, ...request.Option) (*CreateNamespaceOutput, error)
	CreateNamespaceRequest(*CreateNamespaceInput) (*request.Request, *CreateNamespaceOutput)

	CreateRegistryCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateRegistryCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateRegistryCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateRegistry(*CreateRegistryInput) (*CreateRegistryOutput, error)
	CreateRegistryWithContext(byteplus.Context, *CreateRegistryInput, ...request.Option) (*CreateRegistryOutput, error)
	CreateRegistryRequest(*CreateRegistryInput) (*request.Request, *CreateRegistryOutput)

	CreateRepositoryCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateRepositoryCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateRepositoryCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateRepository(*CreateRepositoryInput) (*CreateRepositoryOutput, error)
	CreateRepositoryWithContext(byteplus.Context, *CreateRepositoryInput, ...request.Option) (*CreateRepositoryOutput, error)
	CreateRepositoryRequest(*CreateRepositoryInput) (*request.Request, *CreateRepositoryOutput)

	CreateRobotAccountCommon(*map[string]interface{}) (*map[string]interface{}, error)
	CreateRobotAccountCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	CreateRobotAccountCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	CreateRobotAccount(*CreateRobotAccountInput) (*CreateRobotAccountOutput, error)
	CreateRobotAccountWithContext(byteplus.Context, *CreateRobotAccountInput, ...request.Option) (*CreateRobotAccountOutput, error)
	CreateRobotAccountRequest(*CreateRobotAccountInput) (*request.Request, *CreateRobotAccountOutput)

	DeleteEndpointAclPoliciesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteEndpointAclPoliciesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteEndpointAclPoliciesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteEndpointAclPolicies(*DeleteEndpointAclPoliciesInput) (*DeleteEndpointAclPoliciesOutput, error)
	DeleteEndpointAclPoliciesWithContext(byteplus.Context, *DeleteEndpointAclPoliciesInput, ...request.Option) (*DeleteEndpointAclPoliciesOutput, error)
	DeleteEndpointAclPoliciesRequest(*DeleteEndpointAclPoliciesInput) (*request.Request, *DeleteEndpointAclPoliciesOutput)

	DeleteNamespaceCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteNamespaceCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteNamespaceCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteNamespace(*DeleteNamespaceInput) (*DeleteNamespaceOutput, error)
	DeleteNamespaceWithContext(byteplus.Context, *DeleteNamespaceInput, ...request.Option) (*DeleteNamespaceOutput, error)
	DeleteNamespaceRequest(*DeleteNamespaceInput) (*request.Request, *DeleteNamespaceOutput)

	DeleteRegistryCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteRegistryCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteRegistryCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteRegistry(*DeleteRegistryInput) (*DeleteRegistryOutput, error)
	DeleteRegistryWithContext(byteplus.Context, *DeleteRegistryInput, ...request.Option) (*DeleteRegistryOutput, error)
	DeleteRegistryRequest(*DeleteRegistryInput) (*request.Request, *DeleteRegistryOutput)

	DeleteRepositoryCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteRepositoryCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteRepositoryCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteRepository(*DeleteRepositoryInput) (*DeleteRepositoryOutput, error)
	DeleteRepositoryWithContext(byteplus.Context, *DeleteRepositoryInput, ...request.Option) (*DeleteRepositoryOutput, error)
	DeleteRepositoryRequest(*DeleteRepositoryInput) (*request.Request, *DeleteRepositoryOutput)

	DeleteRobotAccountCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteRobotAccountCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteRobotAccountCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteRobotAccount(*DeleteRobotAccountInput) (*DeleteRobotAccountOutput, error)
	DeleteRobotAccountWithContext(byteplus.Context, *DeleteRobotAccountInput, ...request.Option) (*DeleteRobotAccountOutput, error)
	DeleteRobotAccountRequest(*DeleteRobotAccountInput) (*request.Request, *DeleteRobotAccountOutput)

	DeleteTagsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	DeleteTagsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	DeleteTagsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	DeleteTags(*DeleteTagsInput) (*DeleteTagsOutput, error)
	DeleteTagsWithContext(byteplus.Context, *DeleteTagsInput, ...request.Option) (*DeleteTagsOutput, error)
	DeleteTagsRequest(*DeleteTagsInput) (*request.Request, *DeleteTagsOutput)

	GetAuthorizationTokenCommon(*map[string]interface{}) (*map[string]interface{}, error)
	GetAuthorizationTokenCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetAuthorizationTokenCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetAuthorizationToken(*GetAuthorizationTokenInput) (*GetAuthorizationTokenOutput, error)
	GetAuthorizationTokenWithContext(byteplus.Context, *GetAuthorizationTokenInput, ...request.Option) (*GetAuthorizationTokenOutput, error)
	GetAuthorizationTokenRequest(*GetAuthorizationTokenInput) (*request.Request, *GetAuthorizationTokenOutput)

	GetPublicEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	GetPublicEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetPublicEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetPublicEndpoint(*GetPublicEndpointInput) (*GetPublicEndpointOutput, error)
	GetPublicEndpointWithContext(byteplus.Context, *GetPublicEndpointInput, ...request.Option) (*GetPublicEndpointOutput, error)
	GetPublicEndpointRequest(*GetPublicEndpointInput) (*request.Request, *GetPublicEndpointOutput)

	GetUserCommon(*map[string]interface{}) (*map[string]interface{}, error)
	GetUserCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetUserCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetUser(*GetUserInput) (*GetUserOutput, error)
	GetUserWithContext(byteplus.Context, *GetUserInput, ...request.Option) (*GetUserOutput, error)
	GetUserRequest(*GetUserInput) (*request.Request, *GetUserOutput)

	GetVpcEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	GetVpcEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	GetVpcEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	GetVpcEndpoint(*GetVpcEndpointInput) (*GetVpcEndpointOutput, error)
	GetVpcEndpointWithContext(byteplus.Context, *GetVpcEndpointInput, ...request.Option) (*GetVpcEndpointOutput, error)
	GetVpcEndpointRequest(*GetVpcEndpointInput) (*request.Request, *GetVpcEndpointOutput)

	ListDomainsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListDomainsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListDomainsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListDomains(*ListDomainsInput) (*ListDomainsOutput, error)
	ListDomainsWithContext(byteplus.Context, *ListDomainsInput, ...request.Option) (*ListDomainsOutput, error)
	ListDomainsRequest(*ListDomainsInput) (*request.Request, *ListDomainsOutput)

	ListNamespacesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListNamespacesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListNamespacesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListNamespaces(*ListNamespacesInput) (*ListNamespacesOutput, error)
	ListNamespacesWithContext(byteplus.Context, *ListNamespacesInput, ...request.Option) (*ListNamespacesOutput, error)
	ListNamespacesRequest(*ListNamespacesInput) (*request.Request, *ListNamespacesOutput)

	ListRegistriesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListRegistriesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListRegistriesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListRegistries(*ListRegistriesInput) (*ListRegistriesOutput, error)
	ListRegistriesWithContext(byteplus.Context, *ListRegistriesInput, ...request.Option) (*ListRegistriesOutput, error)
	ListRegistriesRequest(*ListRegistriesInput) (*request.Request, *ListRegistriesOutput)

	ListRepositoriesCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListRepositoriesCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListRepositoriesCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListRepositories(*ListRepositoriesInput) (*ListRepositoriesOutput, error)
	ListRepositoriesWithContext(byteplus.Context, *ListRepositoriesInput, ...request.Option) (*ListRepositoriesOutput, error)
	ListRepositoriesRequest(*ListRepositoriesInput) (*request.Request, *ListRepositoriesOutput)

	ListRobotAccountsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListRobotAccountsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListRobotAccountsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListRobotAccounts(*ListRobotAccountsInput) (*ListRobotAccountsOutput, error)
	ListRobotAccountsWithContext(byteplus.Context, *ListRobotAccountsInput, ...request.Option) (*ListRobotAccountsOutput, error)
	ListRobotAccountsRequest(*ListRobotAccountsInput) (*request.Request, *ListRobotAccountsOutput)

	ListTagsCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListTagsCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListTagsCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListTags(*ListTagsInput) (*ListTagsOutput, error)
	ListTagsWithContext(byteplus.Context, *ListTagsInput, ...request.Option) (*ListTagsOutput, error)
	ListTagsRequest(*ListTagsInput) (*request.Request, *ListTagsOutput)

	SetUserCommon(*map[string]interface{}) (*map[string]interface{}, error)
	SetUserCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	SetUserCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	SetUser(*SetUserInput) (*SetUserOutput, error)
	SetUserWithContext(byteplus.Context, *SetUserInput, ...request.Option) (*SetUserOutput, error)
	SetUserRequest(*SetUserInput) (*request.Request, *SetUserOutput)

	StartRegistryCommon(*map[string]interface{}) (*map[string]interface{}, error)
	StartRegistryCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	StartRegistryCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	StartRegistry(*StartRegistryInput) (*StartRegistryOutput, error)
	StartRegistryWithContext(byteplus.Context, *StartRegistryInput, ...request.Option) (*StartRegistryOutput, error)
	StartRegistryRequest(*StartRegistryInput) (*request.Request, *StartRegistryOutput)

	UpdatePublicEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	UpdatePublicEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdatePublicEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdatePublicEndpoint(*UpdatePublicEndpointInput) (*UpdatePublicEndpointOutput, error)
	UpdatePublicEndpointWithContext(byteplus.Context, *UpdatePublicEndpointInput, ...request.Option) (*UpdatePublicEndpointOutput, error)
	UpdatePublicEndpointRequest(*UpdatePublicEndpointInput) (*request.Request, *UpdatePublicEndpointOutput)

	UpdateRepositoryCommon(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateRepositoryCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateRepositoryCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateRepository(*UpdateRepositoryInput) (*UpdateRepositoryOutput, error)
	UpdateRepositoryWithContext(byteplus.Context, *UpdateRepositoryInput, ...request.Option) (*UpdateRepositoryOutput, error)
	UpdateRepositoryRequest(*UpdateRepositoryInput) (*request.Request, *UpdateRepositoryOutput)

	UpdateRobotAccountCommon(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateRobotAccountCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateRobotAccountCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateRobotAccount(*UpdateRobotAccountInput) (*UpdateRobotAccountOutput, error)
	UpdateRobotAccountWithContext(byteplus.Context, *UpdateRobotAccountInput, ...request.Option) (*UpdateRobotAccountOutput, error)
	UpdateRobotAccountRequest(*UpdateRobotAccountInput) (*request.Request, *UpdateRobotAccountOutput)

	UpdateRobotAccountPasswordCommon(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateRobotAccountPasswordCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateRobotAccountPasswordCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateRobotAccountPassword(*UpdateRobotAccountPasswordInput) (*UpdateRobotAccountPasswordOutput, error)
	UpdateRobotAccountPasswordWithContext(byteplus.Context, *UpdateRobotAccountPasswordInput, ...request.Option) (*UpdateRobotAccountPasswordOutput, error)
	UpdateRobotAccountPasswordRequest(*UpdateRobotAccountPasswordInput) (*request.Request, *UpdateRobotAccountPasswordOutput)

	UpdateVpcEndpointCommon(*map[string]interface{}) (*map[string]interface{}, error)
	UpdateVpcEndpointCommonWithContext(byteplus.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	UpdateVpcEndpointCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	UpdateVpcEndpoint(*UpdateVpcEndpointInput) (*UpdateVpcEndpointOutput, error)
	UpdateVpcEndpointWithContext(byteplus.Context, *UpdateVpcEndpointInput, ...request.Option) (*UpdateVpcEndpointOutput, error)
	UpdateVpcEndpointRequest(*UpdateVpcEndpointInput) (*request.Request, *UpdateVpcEndpointOutput)
}

var _ CRAPI = (*CR)(nil)
